INSERT INTO business (email,name,address,description,business_type,business_state) VALUES 
('bythewaybakery.com@gmail.com', 'By The Way Bakery', 'bythewaybakery.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('ultimatefitness,queens.com@gmail.com', 'Ultimate Fitness, Queens', 'ultimatefitness,queens.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('naturebliss.com@gmail.com', 'Nature Bliss', 'naturebliss.com', 'This is the description of this business', 'Florist', 'Reported'),
('c-pac/pulse48.com@gmail.com', 'C-Pac/Pulse 48', 'c-pac/pulse48.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('willieos.com@gmail.com', 'Willie OS', 'willieos.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('herballife/saludesvida.com@gmail.com', 'Herbal Life/Salud Es Vida', 'herballife/saludesvida.com', 'This is the description of this business', 'Florist', 'Pending'),
('kaffekuppen.com@gmail.com', 'Kaffe Kuppen', 'kaffekuppen.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('shuko.com@gmail.com', 'Shuko', 'shuko.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('sagarchinese.com@gmail.com', 'Sagar Chinese', 'sagarchinese.com', 'This is the description of this business', 'Florist', 'Pending'),
('zhousyummyrestaurant.com@gmail.com', 'ZhouS Yummy Restaurant', 'zhousyummyrestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('lakelineflorist&giftsinc.com@gmail.com', 'Lakeline Florist & Gifts Inc', 'lakelineflorist&giftsinc.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('cacio&pepe.com@gmail.com', 'Cacio & Pepe', 'cacio&pepe.com', 'This is the description of this business', 'Florist', 'Pending'),
('ontrackbar(o.t.b.).com@gmail.com', 'On Track Bar (O.T.B.)', 'ontrackbar(o.t.b.).com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('thailandcafe.com@gmail.com', 'Thailand Cafe', 'thailandcafe.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('prince’sflowershop.com@gmail.com', 'Prince’s Flower Shop', 'prince’sflowershop.com', 'This is the description of this business', 'Florist', 'Accepted'),
('aryakabobhouse.com@gmail.com', 'Arya Kabob House', 'aryakabobhouse.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('shortys.com@gmail.com', 'ShortyS', 'shortys.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('metropolitan.com@gmail.com', 'Metropolitan', 'metropolitan.com', 'This is the description of this business', 'Florist', 'Reported'),
('nublu.com@gmail.com', 'Nublu', 'nublu.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('doubledragon.com@gmail.com', 'Double Dragon', 'doubledragon.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('dreamevents.com@gmail.com', 'Dream Events', 'dreamevents.com', 'This is the description of this business', 'Florist', 'Reported'),
('yangshappygarden.com@gmail.com', 'YangS Happy Garden', 'yangshappygarden.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('paradisemanor.com@gmail.com', 'Paradise Manor', 'paradisemanor.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('pacinispizzeria.com@gmail.com', 'PaciniS Pizzeria', 'pacinispizzeria.com', 'This is the description of this business', 'Florist', 'Pending'),
('yvonneyvonnerestaurant.com@gmail.com', 'Yvonne Yvonne Restaurant', 'yvonneyvonnerestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('jameswhite&sons.com@gmail.com', 'James White & Sons', 'jameswhite&sons.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('yangsgoodtaste.com@gmail.com', 'YangS Good Taste', 'yangsgoodtaste.com', 'This is the description of this business', 'Florist', 'Reported'),
('caborestaurant.com@gmail.com', 'Cabo Restaurant', 'caborestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('yankeebar&grill.com@gmail.com', 'Yankee Bar & Grill', 'yankeebar&grill.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('chabaflorists.com@gmail.com', 'Chaba Florists', 'chabaflorists.com', 'This is the description of this business', 'Florist', 'Pending'),
('24hourflowers.com@gmail.com', '24 Hour Flowers', '24hourflowers.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('vallspizzeria.com@gmail.com', 'VallS Pizzeria', 'vallspizzeria.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('medusa.com@gmail.com', 'Medusa', 'medusa.com', 'This is the description of this business', 'Florist', 'Pending'),
('bainbridgebakery.com@gmail.com', 'Bainbridge Bakery', 'bainbridgebakery.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('queenscomfortrestaurant.com@gmail.com', 'Queens Comfort Restaurant', 'queenscomfortrestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('bricolagecuratedflorals.com@gmail.com', 'Bricolage Curated Florals', 'bricolagecuratedflorals.com', 'This is the description of this business', 'Florist', 'Pending'),
('barbolonat.com@gmail.com', 'Bar Bolonat', 'barbolonat.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('cafesicily.com@gmail.com', 'Cafe  Sicily', 'cafesicily.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('thefloraldecorator.com@gmail.com', 'The Floral Decorator', 'thefloraldecorator.com', 'This is the description of this business', 'Florist', 'Accepted'),
('villafiorita.com@gmail.com', 'Villa Fiorita', 'villafiorita.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bargreatharry.com@gmail.com', 'Bar Great Harry', 'bargreatharry.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('radiocitypizza.com@gmail.com', 'Radio City Pizza', 'radiocitypizza.com', 'This is the description of this business', 'Florist', 'Reported'),
('onassiscafe.com@gmail.com', 'Onassis Cafe', 'onassiscafe.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('ohlala!crepes,inc.com@gmail.com', 'Oh Lala! Crepes, Inc', 'ohlala!crepes,inc.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('babel.com@gmail.com', 'Babel', 'babel.com', 'This is the description of this business', 'Florist', 'Pending'),
('charlotte’sfiestaflowers.com@gmail.com', 'Charlotte’s Fiesta Flowers', 'charlotte’sfiestaflowers.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('nucafe47.com@gmail.com', 'Nu Cafe 47', 'nucafe47.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('barchuko.com@gmail.com', 'Bar Chuko', 'barchuko.com', 'This is the description of this business', 'Florist', 'Reported'),
('shuka.com@gmail.com', 'Shuka', 'shuka.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bostoncityflorist.com@gmail.com', 'Boston City Florist', 'bostoncityflorist.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('sagarrestaurant.com@gmail.com', 'Sagar Restaurant', 'sagarrestaurant.com', 'This is the description of this business', 'Florist', 'Pending'),
('villafreshitaliankitchen.com@gmail.com', 'Villa Fresh Italian Kitchen', 'villafreshitaliankitchen.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('metromart.com@gmail.com', 'Metro Mart', 'metromart.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('catfish.com@gmail.com', 'Catfish', 'catfish.com', 'This is the description of this business', 'Florist', 'Pending'),
('henry.com@gmail.com', 'Henry', 'henry.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('charleston.com@gmail.com', 'Charleston', 'charleston.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('joysiangrestaurant.com@gmail.com', 'Joy Siang Restaurant', 'joysiangrestaurant.com', 'This is the description of this business', 'Florist', 'Pending'),
('wasabirestaurant.com@gmail.com', 'Wasabi Restaurant', 'wasabirestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('cafe1ofakind.com@gmail.com', 'Cafe 1 Of A Kind', 'cafe1ofakind.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('zumschneider.com@gmail.com', 'Zum Schneider', 'zumschneider.com', 'This is the description of this business', 'Florist', 'Pending'),
('mccormickschmickseafoodrestaurant.com@gmail.com', 'Mccormick Schmick Seafood Restaurant', 'mccormickschmickseafoodrestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('shotsbilliards.com@gmail.com', 'Shots Billiards', 'shotsbilliards.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('flowervision.com@gmail.com', 'Flower Vision', 'flowervision.com', 'This is the description of this business', 'Florist', 'Pending'),
('passionbouquetinc.com@gmail.com', 'Passion Bouquet Inc', 'passionbouquetinc.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('sarkujapan.com@gmail.com', 'Sarku Japan', 'sarkujapan.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('freytag’sflorist.com@gmail.com', 'Freytag’s Florist', 'freytag’sflorist.com', 'This is the description of this business', 'Florist', 'Pending'),
('bajancafe.com@gmail.com', 'Bajan Cafe', 'bajancafe.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('strongplace.com@gmail.com', 'Strong Place', 'strongplace.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('washingtoncommons.com@gmail.com', 'Washington Commons', 'washingtoncommons.com', 'This is the description of this business', 'Florist', 'Pending'),
('diana’sflowershop.com@gmail.com', 'Diana’s Flower Shop', 'diana’sflowershop.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('yogirestaurant.com@gmail.com', 'Yogi Restaurant', 'yogirestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('henrypublic.com@gmail.com', 'Henry Public', 'henrypublic.com', 'This is the description of this business', 'Florist', 'Reported'),
('oliengthairestaurant.com@gmail.com', 'Olieng Thai Restaurant', 'oliengthairestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('dipdip.com@gmail.com', 'Dip Dip', 'dipdip.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('darlingbuds.com@gmail.com', 'Darling Buds', 'darlingbuds.com', 'This is the description of this business', 'Florist', 'Pending'),
('nuhotel.com@gmail.com', 'Nu Hotel', 'nuhotel.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('xunsu.com@gmail.com', 'Xun Su', 'xunsu.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('raesdeli.com@gmail.com', 'RaeS Deli', 'raesdeli.com', 'This is the description of this business', 'Florist', 'Accepted'),
('dinosaurbar-b-que.com@gmail.com', 'Dinosaur Bar-B-Que', 'dinosaurbar-b-que.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('pasteurgrill&noodles.com@gmail.com', 'Pasteur Grill & Noodles', 'pasteurgrill&noodles.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('buds&bowers.com@gmail.com', 'buds&bowers', 'buds&bowers.com', 'This is the description of this business', 'Florist', 'Accepted'),
('dinarataatandazwallstreethotel.com@gmail.com', 'Dina Rata At Andaz Wall Street Hotel', 'dinarataatandazwallstreethotel.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('fernbybostonroseflorist.com@gmail.com', 'Fern by Boston Rose Florist', 'fernbybostonroseflorist.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('wingsflowerexchange.com@gmail.com', 'Wings Flower Exchange', 'wingsflowerexchange.com', 'This is the description of this business', 'Florist', 'Pending'),
('pekingoishi.com@gmail.com', 'Peking Oishi', 'pekingoishi.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('pastafina.com@gmail.com', 'Pastafina', 'pastafina.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('valhalla.com@gmail.com', 'Valhalla', 'valhalla.com', 'This is the description of this business', 'Florist', 'Pending'),
('poet’sgarden.com@gmail.com', 'Poet’s Garden', 'poet’sgarden.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('capponessalumeria.com@gmail.com', 'Cappones Salumeria', 'capponessalumeria.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('ko-sushijapaneserestaurant.com@gmail.com', 'Ko-Sushi Japanese Restaurant', 'ko-sushijapaneserestaurant.com', 'This is the description of this business', 'Florist', 'Pending'),
('kodamasushi.com@gmail.com', 'Kodama Sushi', 'kodamasushi.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('thailandrestaurant.com@gmail.com', 'Thailand Restaurant', 'thailandrestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('nayaexpress.com@gmail.com', 'Naya Express', 'nayaexpress.com', 'This is the description of this business', 'Florist', 'Pending'),
('paradisevenusrestaurant.com@gmail.com', 'Paradise Venus Restaurant', 'paradisevenusrestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('arepaspuesmixtas.com@gmail.com', 'Arepas Pues Mixtas', 'arepaspuesmixtas.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('cafe101.com@gmail.com', 'Cafe 101', 'cafe101.com', 'This is the description of this business', 'Florist', 'Accepted'),
('pacificstandard.com@gmail.com', 'Pacific Standard', 'pacificstandard.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('arturos.com@gmail.com', 'Arturos', 'arturos.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('flowersvassette.com@gmail.com', 'Flowers Vassette', 'flowersvassette.com', 'This is the description of this business', 'Florist', 'Pending'),
('j4hookahlounge.com@gmail.com', 'J4 Hookah Lounge', 'j4hookahlounge.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('zuckersbagel.com@gmail.com', 'ZuckerS Bagel', 'zuckersbagel.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('kafeneo.com@gmail.com', 'Kafeneo', 'kafeneo.com', 'This is the description of this business', 'Florist', 'Accepted'),
('umas.com@gmail.com', 'UmaS', 'umas.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('zimebistro.com@gmail.com', 'Zime Bistro', 'zimebistro.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('jamaicagrillrestaurant.com@gmail.com', 'Jamaica Grill Restaurant', 'jamaicagrillrestaurant.com', 'This is the description of this business', 'Florist', 'Pending'),
('lotusdesigns.com@gmail.com', 'Lotus Designs', 'lotusdesigns.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('table&tulip.com@gmail.com', 'Table & Tulip', 'table&tulip.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('yogomonster.com@gmail.com', 'Yogo Monster', 'yogomonster.com', 'This is the description of this business', 'Florist', 'Pending'),
('proflowers.com@gmail.com', 'ProFlowers', 'proflowers.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('cjbanquetlatino.com@gmail.com', 'C J Banquet Latino', 'cjbanquetlatino.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('nuchas.com@gmail.com', 'Nuchas', 'nuchas.com', 'This is the description of this business', 'Florist', 'Accepted'),
('argotea.com@gmail.com', 'Argo Tea', 'argotea.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('artofbloom.com@gmail.com', 'Art of Bloom', 'artofbloom.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('navy.com@gmail.com', 'Navy', 'navy.com', 'This is the description of this business', 'Florist', 'Accepted'),
('intotea.com@gmail.com', 'Intotea', 'intotea.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('z-twodiner&lounge.com@gmail.com', 'Z-Two Diner & Lounge', 'z-twodiner&lounge.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('nuccis.com@gmail.com', 'Nuccis', 'nuccis.com', 'This is the description of this business', 'Florist', 'Reported'),
('passionposies.com@gmail.com', 'Passion Posies', 'passionposies.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('edamamacutecutsandmore.com@gmail.com', 'Edamama Cute Cuts And More', 'edamamacutecutsandmore.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('yogurtdownunder.com@gmail.com', 'Yogurt Down Under', 'yogurtdownunder.com', 'This is the description of this business', 'Florist', 'Accepted'),
('bajafresh.com@gmail.com', 'Baja Fresh', 'bajafresh.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('mccoy.com@gmail.com', 'Mccoy', 'mccoy.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('bait&hook.com@gmail.com', 'Bait & Hook', 'bait&hook.com', 'This is the description of this business', 'Florist', 'Pending'),
('barcyrknyc.com@gmail.com', 'Bar Cyrk Nyc', 'barcyrknyc.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('metrosushicafe.com@gmail.com', 'Metro Sushi Cafe', 'metrosushicafe.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('articulturedesigns.com@gmail.com', 'Articulture Designs', 'articulturedesigns.com', 'This is the description of this business', 'Florist', 'Accepted'),
('zaghloulgrill.com@gmail.com', 'Zaghloul Grill', 'zaghloulgrill.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('flowersarehappy.com@gmail.com', 'Flowers Are Happy', 'flowersarehappy.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('ukuscafe.com@gmail.com', 'Ukus Cafe', 'ukuscafe.com', 'This is the description of this business', 'Florist', 'Pending'),
('flowerfilter.com@gmail.com', 'Flower Filter', 'flowerfilter.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('dimes.com@gmail.com', 'Dimes', 'dimes.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('onceuponatart.com@gmail.com', 'Once Upon A Tart', 'onceuponatart.com', 'This is the description of this business', 'Florist', 'Reported'),
('cieloristorante.com@gmail.com', 'Cielo Ristorante', 'cieloristorante.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('kaffe1668.com@gmail.com', 'Kaffe 1668', 'kaffe1668.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('willowroad.com@gmail.com', 'Willow Road', 'willowroad.com', 'This is the description of this business', 'Florist', 'Reported'),
('henryslocal.com@gmail.com', 'Henrys Local', 'henryslocal.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('henrysexpresscoffeeshop.com@gmail.com', 'Henrys Express Coffee Shop', 'henrysexpresscoffeeshop.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('studio.com@gmail.com', 'Studio', 'studio.com', 'This is the description of this business', 'Florist', 'Reported'),
('zabbcity.com@gmail.com', 'Zabb City', 'zabbcity.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('oishisushi.com@gmail.com', 'Oishi Sushi', 'oishisushi.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('pimpollo.com@gmail.com', 'Pimpollo', 'pimpollo.com', 'This is the description of this business', 'Florist', 'Pending'),
('theflowerbucket.com@gmail.com', 'The Flower Bucket', 'theflowerbucket.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('shrine/yatenga.com@gmail.com', 'Shrine/Yatenga', 'shrine/yatenga.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('xpresspizzeria.com@gmail.com', 'Xpress Pizzeria', 'xpresspizzeria.com', 'This is the description of this business', 'Florist', 'Accepted'),
('argoteacafe.com@gmail.com', 'Argo Tea Cafe', 'argoteacafe.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('wimpysrestaurant5.com@gmail.com', 'WimpyS Restaurant 5', 'wimpysrestaurant5.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('zuccheroepomodori.com@gmail.com', 'Zucchero E Pomodori', 'zuccheroepomodori.com', 'This is the description of this business', 'Florist', 'Reported'),
('eddiefancyfood.com@gmail.com', 'Eddie Fancy Food', 'eddiefancyfood.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('caterinaspizza.com@gmail.com', 'Caterinas Pizza', 'caterinaspizza.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('exoticflowers.com@gmail.com', 'Exotic Flowers', 'exoticflowers.com', 'This is the description of this business', 'Florist', 'Reported'),
('nbaemployercafeteria.com@gmail.com', 'Nba Employer Cafeteria', 'nbaemployercafeteria.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('henricasrestaurant.com@gmail.com', 'Henricas Restaurant', 'henricasrestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('openlotusgarden.com@gmail.com', 'Open Lotus Garden', 'openlotusgarden.com', 'This is the description of this business', 'Florist', 'Reported'),
('wildlotus.com@gmail.com', 'Wild Lotus', 'wildlotus.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('yogurtlacrepe.com@gmail.com', 'Yogurt La Crepe', 'yogurtlacrepe.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('8petals.com@gmail.com', '8 Petals', '8petals.com', 'This is the description of this business', 'Florist', 'Pending'),
('nusushi.com@gmail.com', 'Nu Sushi', 'nusushi.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('kobesushi.com@gmail.com', 'Kobe Sushi', 'kobesushi.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('byungchunsoondae.com@gmail.com', 'Byung Chun Soon Dae', 'byungchunsoondae.com', 'This is the description of this business', 'Florist', 'Reported'),
('caeldonia.com@gmail.com', 'Caeldonia', 'caeldonia.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('zhongzheng26restaurantinc.com@gmail.com', 'Zhong Zheng 26 Restaurant Inc', 'zhongzheng26restaurantinc.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('texasbloomsandgifts.com@gmail.com', 'Texas Blooms and Gifts', 'texasbloomsandgifts.com', 'This is the description of this business', 'Florist', 'Reported'),
('koi.com@gmail.com', 'Koi', 'koi.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('raffles.com@gmail.com', 'Raffles', 'raffles.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('joyiikitchen.com@gmail.com', 'Joy Ii Kitchen', 'joyiikitchen.com', 'This is the description of this business', 'Florist', 'Reported'),
('wasabi.com@gmail.com', 'Wasabi', 'wasabi.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('thalassa.com@gmail.com', 'Thalassa', 'thalassa.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('glassflower.com@gmail.com', 'Glass Flower', 'glassflower.com', 'This is the description of this business', 'Florist', 'Reported'),
('caesarspalace.com@gmail.com', 'Caesars Palace', 'caesarspalace.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bzgrill.com@gmail.com', 'Bz Grill', 'bzgrill.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('lonestarbloom.com@gmail.com', 'Lone Star Bloom', 'lonestarbloom.com', 'This is the description of this business', 'Florist', 'Accepted'),
('irishpunt.com@gmail.com', 'Irish Punt', 'irishpunt.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('oligarch.com@gmail.com', 'Oligarch', 'oligarch.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('sataymalaysian.com@gmail.com', 'Satay Malaysian', 'sataymalaysian.com', 'This is the description of this business', 'Florist', 'Reported'),
('valbellan.y..com@gmail.com', 'Valbella N.Y.', 'valbellan.y..com', 'This is the description of this business', 'Restaurant', 'Pending'),
('c2cafe.com@gmail.com', 'C2 Cafe', 'c2cafe.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('cabareteseafood.com@gmail.com', 'Cabarete Seafood', 'cabareteseafood.com', 'This is the description of this business', 'Florist', 'Pending'),
('always&foreverflorist.com@gmail.com', 'Always & Forever Florist', 'always&foreverflorist.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('millstavern.com@gmail.com', 'Mills Tavern', 'millstavern.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('enchantedflorist.com@gmail.com', 'Enchanted Florist', 'enchantedflorist.com', 'This is the description of this business', 'Florist', 'Accepted'),
('eddyseats.com@gmail.com', 'Eddys Eats', 'eddyseats.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('vamos.com@gmail.com', 'Vamos', 'vamos.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('villacastillorestaurantcorp.com@gmail.com', 'Villa Castillo Restaurant Corp', 'villacastillorestaurantcorp.com', 'This is the description of this business', 'Florist', 'Pending'),
('baileyscornerpub.com@gmail.com', 'Baileys Corner Pub', 'baileyscornerpub.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('flowerfolk.com@gmail.com', 'Flower Folk', 'flowerfolk.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('paradorcaleno.com@gmail.com', 'Parador Caleno', 'paradorcaleno.com', 'This is the description of this business', 'Florist', 'Reported'),
('arturospizza.com@gmail.com', 'Arturos Pizza', 'arturospizza.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('kahluascafe&restaurant.com@gmail.com', 'KahluaS Cafe & Restaurant', 'kahluascafe&restaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('glowingflowers.com@gmail.com', 'Glowing Flowers', 'glowingflowers.com', 'This is the description of this business', 'Florist', 'Accepted'),
('thornyroses.com@gmail.com', 'Thorny Roses', 'thornyroses.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('petals&leaves.com@gmail.com', 'Petals & Leaves', 'petals&leaves.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('nuccissouth.com@gmail.com', 'NucciS South', 'nuccissouth.com', 'This is the description of this business', 'Florist', 'Accepted'),
('arianadeli.com@gmail.com', 'Ariana Deli', 'arianadeli.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('flowermaximum.com@gmail.com', 'Flower Maximum', 'flowermaximum.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('diningroom.com@gmail.com', 'Dining Room', 'diningroom.com', 'This is the description of this business', 'Florist', 'Accepted'),
('blossom&bows.com@gmail.com', 'Blossom & Bows', 'blossom&bows.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('miloscafe.com@gmail.com', 'Milos Cafe', 'miloscafe.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('mccanncafeteria.com@gmail.com', 'Mccann Cafeteria', 'mccanncafeteria.com', 'This is the description of this business', 'Florist', 'Reported'),
('irvingglickfloristshop.com@gmail.com', 'Irving Glick Florist Shop', 'irvingglickfloristshop.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('edslobsterbar.com@gmail.com', 'Eds Lobster Bar', 'edslobsterbar.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('windfall.com@gmail.com', 'Windfall', 'windfall.com', 'This is the description of this business', 'Florist', 'Reported'),
('bahrche.com@gmail.com', 'Bahr Che', 'bahrche.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('yunnankitchen.com@gmail.com', 'Yunnan Kitchen', 'yunnankitchen.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('cielocafe.com@gmail.com', 'Cielo Cafe', 'cielocafe.com', 'This is the description of this business', 'Florist', 'Pending'),
('aflowerjunction.com@gmail.com', 'A Flower Junction', 'aflowerjunction.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('petalmetsugar.com@gmail.com', 'Petal Met Sugar', 'petalmetsugar.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('zumajapaneserestaurantnewyork.com@gmail.com', 'Zuma Japanese Restaurant New York', 'zumajapaneserestaurantnewyork.com', 'This is the description of this business', 'Florist', 'Accepted'),
('strombolipizza.com@gmail.com', 'Stromboli Pizza', 'strombolipizza.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('tulipanna.com@gmail.com', 'Tulipanna', 'tulipanna.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('robin’sflowershop.com@gmail.com', 'Robin’s Flower Shop', 'robin’sflowershop.com', 'This is the description of this business', 'Florist', 'Accepted'),
('nsefiftysix.com@gmail.com', 'Nse Fifty Six', 'nsefiftysix.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('milliondeli.com@gmail.com', 'Million Deli', 'milliondeli.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('pieface.com@gmail.com', 'Pie Face', 'pieface.com', 'This is the description of this business', 'Florist', 'Pending'),
('pinchfooddesign.com@gmail.com', 'Pinch Food Design', 'pinchfooddesign.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('mondayblooms.com@gmail.com', 'Monday Blooms', 'mondayblooms.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('happybirthdayflowers.com@gmail.com', 'Happy Birthday Flowers', 'happybirthdayflowers.com', 'This is the description of this business', 'Florist', 'Reported'),
('ohtaisho.com@gmail.com', 'Oh Taisho', 'ohtaisho.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('mercedesflowers.com@gmail.com', 'Mercedes Flowers', 'mercedesflowers.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('yogurt&company.com@gmail.com', 'Yogurt & Company', 'yogurt&company.com', 'This is the description of this business', 'Florist', 'Accepted'),
('shuimeicafe.com@gmail.com', 'Shui Mei Cafe', 'shuimeicafe.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('ulysses.com@gmail.com', 'Ulysses', 'ulysses.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('paradisony.com@gmail.com', 'Paradiso Ny', 'paradisony.com', 'This is the description of this business', 'Florist', 'Accepted'),
('joyluckseafoodrestaurant.com@gmail.com', 'Joy Luck Seafood Restaurant', 'joyluckseafoodrestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('yogurtberry.com@gmail.com', 'Yogurtberry', 'yogurtberry.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('tacohouse.com@gmail.com', 'Taco House', 'tacohouse.com', 'This is the description of this business', 'Florist', 'Pending'),
('valentinospizza.com@gmail.com', 'ValentinoS Pizza', 'valentinospizza.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('saritasbakery.com@gmail.com', 'SaritaS Bakery', 'saritasbakery.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('arianascateringhall.com@gmail.com', 'Arianas Catering Hall', 'arianascateringhall.com', 'This is the description of this business', 'Florist', 'Pending'),
('arianakebabhouse.com@gmail.com', 'Ariana Kebab House', 'arianakebabhouse.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('vamosaltequila.com@gmail.com', 'Vamos Al Tequila', 'vamosaltequila.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('parkcrestfloraldesign.com@gmail.com', 'ParkCrest Floral Design', 'parkcrestfloraldesign.com', 'This is the description of this business', 'Florist', 'Accepted'),
('barboulud.com@gmail.com', 'Bar Boulud', 'barboulud.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('theflowerstudio.com@gmail.com', 'The Flower Studio', 'theflowerstudio.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('naturalsurroundings.com@gmail.com', 'Natural Surroundings', 'naturalsurroundings.com', 'This is the description of this business', 'Florist', 'Accepted'),
('sarkujapanteriyaki&sushiexpress.com@gmail.com', 'Sarku Japan Teriyaki & Sushi Express', 'sarkujapanteriyaki&sushiexpress.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('shortstoprestaurant.com@gmail.com', 'Short Stop Restaurant', 'shortstoprestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('centralsquareflorist.com@gmail.com', 'Central Square Florist', 'centralsquareflorist.com', 'This is the description of this business', 'Florist', 'Reported'),
('thefolly.com@gmail.com', 'The Folly', 'thefolly.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('wasabisushi.com@gmail.com', 'Wasabi Sushi', 'wasabisushi.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('cacioevino.com@gmail.com', 'Cacio E Vino', 'cacioevino.com', 'This is the description of this business', 'Florist', 'Pending'),
('j.e.bakery.com@gmail.com', 'J.E. Bakery', 'j.e.bakery.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('babyolive.com@gmail.com', 'Baby Olive', 'babyolive.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('c.u.n.ycafe.com@gmail.com', 'C.U.N.Y Cafe', 'c.u.n.ycafe.com', 'This is the description of this business', 'Florist', 'Accepted'),
('koa-21llc.com@gmail.com', 'Koa-21 Llc', 'koa-21llc.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('zuzuramen.com@gmail.com', 'Zuzu Ramen', 'zuzuramen.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('jamaicafishmarket.com@gmail.com', 'Jamaica Fish Market', 'jamaicafishmarket.com', 'This is the description of this business', 'Florist', 'Reported'),
('metropizza.com@gmail.com', 'Metro Pizza', 'metropizza.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('zazaborom.com@gmail.com', 'Za Zaborom', 'zazaborom.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('c&bpizza.com@gmail.com', 'C & B Pizza', 'c&bpizza.com', 'This is the description of this business', 'Florist', 'Accepted'),
('olioepiu.com@gmail.com', 'Olio E Piu', 'olioepiu.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('plantparty.com@gmail.com', 'Plant Party', 'plantparty.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bloomey’s.com@gmail.com', 'Bloomey’s', 'bloomey’s.com', 'This is the description of this business', 'Florist', 'Accepted'),
('jackdemseyspub.com@gmail.com', 'Jack DemseyS Pub', 'jackdemseyspub.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('diningclubrockefellercenter.com@gmail.com', 'Dining Club Rockefeller Center', 'diningclubrockefellercenter.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('divineflowers.com@gmail.com', 'Divine Flowers', 'divineflowers.com', 'This is the description of this business', 'Florist', 'Pending'),
('kowongrestaurant.com@gmail.com', 'Ko Wong Restaurant', 'kowongrestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('zaircafe.com@gmail.com', 'Zair Cafe', 'zaircafe.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('capribakery.com@gmail.com', 'Capri Bakery', 'capribakery.com', 'This is the description of this business', 'Florist', 'Reported'),
('baisrochel.com@gmail.com', 'Bais Rochel', 'baisrochel.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('wilmajean.com@gmail.com', 'Wilma Jean', 'wilmajean.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('gardengirl.com@gmail.com', 'Garden Girl', 'gardengirl.com', 'This is the description of this business', 'Florist', 'Reported'),
('queensdumplinandeverythingrestaurant.com@gmail.com', 'Queens Dumplin And Everything Restaurant', 'queensdumplinandeverythingrestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('doublewidebar.com@gmail.com', 'Double Wide Bar', 'doublewidebar.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('freshflowermarket.com@gmail.com', 'Fresh Flower Market', 'freshflowermarket.com', 'This is the description of this business', 'Florist', 'Reported'),
('barchord.com@gmail.com', 'Bar Chord', 'barchord.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('doubledutchespresso.com@gmail.com', 'Double Dutch Espresso', 'doubledutchespresso.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('babalu.com@gmail.com', 'Babalu', 'babalu.com', 'This is the description of this business', 'Florist', 'Accepted'),
('rafi786.com@gmail.com', 'Rafi 786', 'rafi786.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('fashionflowers.com@gmail.com', 'Fashion Flowers', 'fashionflowers.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('italflorist.com@gmail.com', 'Ital Florist', 'italflorist.com', 'This is the description of this business', 'Florist', 'Reported'),
('strokosgourmetdeli.com@gmail.com', 'Strokos Gourmet Deli', 'strokosgourmetdeli.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('selectedflower.com@gmail.com', 'Selected Flower', 'selectedflower.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('olgasrestaurant.com@gmail.com', 'OlgaS Restaurant', 'olgasrestaurant.com', 'This is the description of this business', 'Florist', 'Reported'),
('casapepe.com@gmail.com', 'Casa Pepe', 'casapepe.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('pacificosfinefoods.com@gmail.com', 'Pacificos Fine Foods', 'pacificosfinefoods.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('theflowercrew.com@gmail.com', 'The Flower Crew', 'theflowercrew.com', 'This is the description of this business', 'Florist', 'Reported'),
('rainbowbouquet.com@gmail.com', 'Rainbow Bouquet', 'rainbowbouquet.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('eddiesdeli&pizza.com@gmail.com', 'Eddies Deli & Pizza', 'eddiesdeli&pizza.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('elabuelogozon.com@gmail.com', 'El Abuelo Gozon', 'elabuelogozon.com', 'This is the description of this business', 'Florist', 'Reported'),
('yofreshnewyork.com@gmail.com', 'Yofresh New York', 'yofreshnewyork.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('babaghanouge.com@gmail.com', 'Baba Ghanouge', 'babaghanouge.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('vallescafe.com@gmail.com', 'ValleS Cafe', 'vallescafe.com', 'This is the description of this business', 'Florist', 'Accepted'),
('bahbkabctahbka.com@gmail.com', 'Bahbka Bctahbka', 'bahbkabctahbka.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('tacohut.com@gmail.com', 'Taco Hut', 'tacohut.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('c&bluncheonette.com@gmail.com', 'C & B Luncheonette', 'c&bluncheonette.com', 'This is the description of this business', 'Florist', 'Reported'),
('aruneethai.com@gmail.com', 'Arunee Thai', 'aruneethai.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('loveandfleurs.com@gmail.com', 'Love and Fleurs', 'loveandfleurs.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('egidiopastry.com@gmail.com', 'Egidio Pastry', 'egidiopastry.com', 'This is the description of this business', 'Florist', 'Reported'),
('arepasgrill.com@gmail.com', 'Arepas Grill', 'arepasgrill.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('nbc.com@gmail.com', 'Nbc', 'nbc.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('thalia.com@gmail.com', 'Thalia', 'thalia.com', 'This is the description of this business', 'Florist', 'Pending'),
('doublehappykitchen.com@gmail.com', 'Double Happy Kitchen', 'doublehappykitchen.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('blossomhouse.com@gmail.com', 'Blossom House', 'blossomhouse.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('dinospizza.com@gmail.com', 'Dinos Pizza', 'dinospizza.com', 'This is the description of this business', 'Florist', 'Pending'),
('zhiqingactivitycenter.com@gmail.com', 'Zhiqing Activity Center', 'zhiqingactivitycenter.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('bloomingtrails.com@gmail.com', 'Blooming Trails', 'bloomingtrails.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('j.j.bubbles.com@gmail.com', 'J.J. Bubbles', 'j.j.bubbles.com', 'This is the description of this business', 'Florist', 'Accepted'),
('charlessally&charles.com@gmail.com', 'Charles Sally & Charles', 'charlessally&charles.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('frenchbouquet.com@gmail.com', 'French Bouquet', 'frenchbouquet.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('eisenbergssandwichshop.com@gmail.com', 'Eisenbergs Sandwich Shop', 'eisenbergssandwichshop.com', 'This is the description of this business', 'Florist', 'Reported'),
('thefoodhut.com@gmail.com', 'The Food Hut', 'thefoodhut.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('paradiserestaurantinc..com@gmail.com', 'Paradise Restaurant Inc.', 'paradiserestaurantinc..com', 'This is the description of this business', 'Restaurant', 'Pending'),
('strokospizzadeli.com@gmail.com', 'Strokos Pizza Deli', 'strokospizzadeli.com', 'This is the description of this business', 'Florist', 'Pending'),
('sashascoffee.com@gmail.com', 'SashaS Coffee', 'sashascoffee.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('yogurty23inc.com@gmail.com', 'Yogurt Y23 Inc', 'yogurty23inc.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('z-onediner&lounge.com@gmail.com', 'Z-One Diner & Lounge', 'z-onediner&lounge.com', 'This is the description of this business', 'Florist', 'Pending'),
('valenciacoffeeroom.com@gmail.com', 'Valencia Coffee Room', 'valenciacoffeeroom.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bahiarestaurant&cafe.com@gmail.com', 'Bahia Restaurant & Cafe', 'bahiarestaurant&cafe.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('winxinkitchen/tacoking.com@gmail.com', 'Win Xin Kitchen/Taco King', 'winxinkitchen/tacoking.com', 'This is the description of this business', 'Florist', 'Reported'),
('arianitasrestaurant.com@gmail.com', 'Arianitas Restaurant', 'arianitasrestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('zutto.com@gmail.com', 'Zutto', 'zutto.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('caedmonschoolwinsteadcaterers.com@gmail.com', 'Caedmon School Winstead Caterers', 'caedmonschoolwinsteadcaterers.com', 'This is the description of this business', 'Florist', 'Pending'),
('doublerainbow.com@gmail.com', 'Double Rainbow', 'doublerainbow.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('sarkurajapan.com@gmail.com', 'Sarkura Japan', 'sarkurajapan.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('rafele.com@gmail.com', 'Rafele', 'rafele.com', 'This is the description of this business', 'Florist', 'Reported'),
('henriettahudson.com@gmail.com', 'Henrietta Hudson', 'henriettahudson.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('jamaicabreezerestaurant.com@gmail.com', 'Jamaica Breeze Restaurant', 'jamaicabreezerestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('aretskyspatroon.com@gmail.com', 'Aretskys Patroon', 'aretskyspatroon.com', 'This is the description of this business', 'Florist', 'Pending'),
('blossom’sfloralartistry.com@gmail.com', 'Blossom’s Floral Artistry', 'blossom’sfloralartistry.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('piepiepizza.com@gmail.com', 'Pie Pie Pizza', 'piepiepizza.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('alibleuflowers&gifts.com@gmail.com', 'Ali Bleu Flowers & Gifts', 'alibleuflowers&gifts.com', 'This is the description of this business', 'Florist', 'Reported'),
('kobeyaki.com@gmail.com', 'Kobeyaki', 'kobeyaki.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('baisushi.com@gmail.com', 'Bai Sushi', 'baisushi.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('theforkbar&grill.com@gmail.com', 'The Fork Bar & Grill', 'theforkbar&grill.com', 'This is the description of this business', 'Florist', 'Accepted'),
('bloom&bud.com@gmail.com', 'Bloom & Bud', 'bloom&bud.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('xpressions.com@gmail.com', 'Xpressions', 'xpressions.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('babacool.com@gmail.com', 'Baba Cool', 'babacool.com', 'This is the description of this business', 'Florist', 'Accepted'),
('sprime.com@gmail.com', 'S Prime', 'sprime.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('rosesonly.com@gmail.com', 'Roses Only', 'rosesonly.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('byblos.com@gmail.com', 'Byblos', 'byblos.com', 'This is the description of this business', 'Florist', 'Accepted'),
('teleflora.com@gmail.com', 'TeleFlora', 'teleflora.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('pastai.com@gmail.com', 'Pastai', 'pastai.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('gardenfresh.com@gmail.com', 'Garden Fresh', 'gardenfresh.com', 'This is the description of this business', 'Florist', 'Reported'),
('showpalace.com@gmail.com', 'Show Palace', 'showpalace.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('cactus.com@gmail.com', 'Cactus', 'cactus.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('charlespizzeria.com@gmail.com', 'Charles Pizzeria', 'charlespizzeria.com', 'This is the description of this business', 'Florist', 'Accepted'),
('cjsbar&lounge.com@gmail.com', 'C Js Bar & Lounge', 'cjsbar&lounge.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('thamma.com@gmail.com', 'Thamma', 'thamma.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bairesbakery.com@gmail.com', 'Baires Bakery', 'bairesbakery.com', 'This is the description of this business', 'Florist', 'Pending'),
('smac.com@gmail.com', 'SMac', 'smac.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('rightchoice.com@gmail.com', 'Right Choice', 'rightchoice.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('henrysend.com@gmail.com', 'Henrys End', 'henrysend.com', 'This is the description of this business', 'Florist', 'Reported'),
('pacos.com@gmail.com', 'PacoS', 'pacos.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('kodarestaurant&lounge.com@gmail.com', 'Koda Restaurant & Lounge', 'kodarestaurant&lounge.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('pillow.com@gmail.com', 'Pillow', 'pillow.com', 'This is the description of this business', 'Florist', 'Accepted'),
('doublehappyrestaurant.com@gmail.com', 'Double Happy Restaurant', 'doublehappyrestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('krazydaizies.com@gmail.com', 'Krazy Daizies', 'krazydaizies.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('greenitplantsco..com@gmail.com', 'Greenit Plants Co.', 'greenitplantsco..com', 'This is the description of this business', 'Florist', 'Accepted'),
('metrostarcoffeeshop.com@gmail.com', 'Metro Star Coffee Shop', 'metrostarcoffeeshop.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('yankeeclipper.com@gmail.com', 'Yankee Clipper', 'yankeeclipper.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('ziemekscafellc.com@gmail.com', 'ZiemekS Cafe Llc', 'ziemekscafellc.com', 'This is the description of this business', 'Florist', 'Pending'),
('kosushi.com@gmail.com', 'Ko Sushi', 'kosushi.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('packardcafe.com@gmail.com', 'Packard  Cafe', 'packardcafe.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('meditteraneangrill.com@gmail.com', 'Meditteranean Grill', 'meditteraneangrill.com', 'This is the description of this business', 'Florist', 'Reported'),
('villaerasamo.com@gmail.com', 'Villa Erasamo', 'villaerasamo.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('j.d.ssaloonbar.com@gmail.com', 'J.D.S Saloon Bar', 'j.d.ssaloonbar.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bake&thingsrestaurant.com@gmail.com', 'Bake & Things Restaurant', 'bake&thingsrestaurant.com', 'This is the description of this business', 'Florist', 'Pending'),
('urbanstems.com@gmail.com', 'Urban Stems', 'urbanstems.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('kaffkafe.com@gmail.com', 'Kaff Kafe', 'kaffkafe.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('winchesterspub.com@gmail.com', 'Winchesters Pub', 'winchesterspub.com', 'This is the description of this business', 'Florist', 'Reported'),
('pastelescapy.com@gmail.com', 'Pasteles Capy', 'pastelescapy.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bakeandthingsrestaurant.com@gmail.com', 'Bake And Things Restaurant', 'bakeandthingsrestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('piepieqcafe.com@gmail.com', 'Pie Pie Q Cafe', 'piepieqcafe.com', 'This is the description of this business', 'Florist', 'Accepted'),
('babygrand.com@gmail.com', 'Baby Grand', 'babygrand.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('eilatrestaurant.com@gmail.com', 'Eilat Restaurant', 'eilatrestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('pie.com@gmail.com', 'Pie', 'pie.com', 'This is the description of this business', 'Florist', 'Pending'),
('xtreme.com@gmail.com', 'Xtreme', 'xtreme.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('henrys.com@gmail.com', 'Henrys', 'henrys.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('babaghanoush.com@gmail.com', 'Babaghanoush', 'babaghanoush.com', 'This is the description of this business', 'Florist', 'Accepted'),
('metronutrition.com@gmail.com', 'Metro Nutrition', 'metronutrition.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bellaflorist.com@gmail.com', 'Bella Florist', 'bellaflorist.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('jamaicabreezenyc.com@gmail.com', 'Jamaica Breeze Nyc', 'jamaicabreezenyc.com', 'This is the description of this business', 'Florist', 'Reported'),
('sdynasty.com@gmail.com', 'S Dynasty', 'sdynasty.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('ironchefhouse.com@gmail.com', 'Iron Chef House', 'ironchefhouse.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('yogorino.com@gmail.com', 'Yogorino', 'yogorino.com', 'This is the description of this business', 'Florist', 'Reported'),
('petalpost.com@gmail.com', 'Petal Post', 'petalpost.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('aria.com@gmail.com', 'Aria', 'aria.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('judy’spetal&blooms.com@gmail.com', 'Judy’s Petal & Blooms', 'judy’spetal&blooms.com', 'This is the description of this business', 'Florist', 'Accepted'),
('nayelinrestaurant.com@gmail.com', 'Nayelin Restaurant', 'nayelinrestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('cachapasymas.com@gmail.com', 'Cachapas Y Mas', 'cachapasymas.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('rainbowflorists.com@gmail.com', 'Rainbow Florists', 'rainbowflorists.com', 'This is the description of this business', 'Florist', 'Reported'),
('canadaflowers.com@gmail.com', 'Canada Flowers', 'canadaflowers.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('flowerhut.com@gmail.com', 'Flower Hut', 'flowerhut.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('prodigyflower.com@gmail.com', 'Prodigy Flower', 'prodigyflower.com', 'This is the description of this business', 'Florist', 'Pending'),
('babboristoranteeenoteca.com@gmail.com', 'Babbo Ristorante E Enoteca', 'babboristoranteeenoteca.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('tacocity.com@gmail.com', 'Taco City', 'tacocity.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('pieces.com@gmail.com', 'Pieces', 'pieces.com', 'This is the description of this business', 'Florist', 'Reported'),
('ultimatebakery.com@gmail.com', 'Ultimate Bakery', 'ultimatebakery.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('barbruno.com@gmail.com', 'Bar Bruno', 'barbruno.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('nuccisrestaurant.com@gmail.com', 'NucciS Restaurant', 'nuccisrestaurant.com', 'This is the description of this business', 'Florist', 'Reported'),
('heraldsquaremarket.com@gmail.com', 'Herald Square Market', 'heraldsquaremarket.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('radissonjfk-cafeoneforty.com@gmail.com', 'Radisson Jfk- Cafe One Forty', 'radissonjfk-cafeoneforty.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('breathtakingblooms.com@gmail.com', 'Breathtaking Blooms', 'breathtakingblooms.com', 'This is the description of this business', 'Florist', 'Pending'),
('winhingfreshtortillas&taco.com@gmail.com', 'Win Hing Fresh Tortillas & Taco', 'winhingfreshtortillas&taco.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('winhou.com@gmail.com', 'Win Hou', 'winhou.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('yura&companyonmadison.com@gmail.com', 'Yura & Company On Madison', 'yura&companyonmadison.com', 'This is the description of this business', 'Florist', 'Reported'),
('jacmaochinesecuisine.com@gmail.com', 'Jac Mao Chinese Cuisine', 'jacmaochinesecuisine.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('zumstammtisch.com@gmail.com', 'Zum Stammtisch', 'zumstammtisch.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('kingflorist.com@gmail.com', 'King Florist', 'kingflorist.com', 'This is the description of this business', 'Florist', 'Accepted'),
('paradou.com@gmail.com', 'Paradou', 'paradou.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('charlesalehouse.com@gmail.com', 'Charles Ale House', 'charlesalehouse.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('yogurtcity.com@gmail.com', 'Yogurt City', 'yogurtcity.com', 'This is the description of this business', 'Florist', 'Pending'),
('rosesretailer.com@gmail.com', 'Roses Retailer', 'rosesretailer.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('queenslibraryemployeecafeteria.com@gmail.com', 'Queens Library Employee Cafeteria', 'queenslibraryemployeecafeteria.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('wasan.com@gmail.com', 'Wasan', 'wasan.com', 'This is the description of this business', 'Florist', 'Accepted'),
('kahve.com@gmail.com', 'Kahve', 'kahve.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('yogurtcouture.com@gmail.com', 'Yogurt Couture', 'yogurtcouture.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('butterflyphilosophy.com@gmail.com', 'Butterfly Philosophy', 'butterflyphilosophy.com', 'This is the description of this business', 'Florist', 'Pending'),
('margotblairfloral.com@gmail.com', 'Margot Blair Floral', 'margotblairfloral.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('sagdiana.com@gmail.com', 'Sagdiana', 'sagdiana.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('joygardenrestaurant.com@gmail.com', 'Joy Garden Restaurant', 'joygardenrestaurant.com', 'This is the description of this business', 'Florist', 'Pending'),
('s&spizzeriacorp.com@gmail.com', 'S&S Pizzeria Corp', 's&spizzeriacorp.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('verbenafloraldesign.com@gmail.com', 'Verbena Floral Design', 'verbenafloraldesign.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('artopoliscafe.com@gmail.com', 'Artopolis Cafe', 'artopoliscafe.com', 'This is the description of this business', 'Florist', 'Pending'),
('cappuccinocafe.com@gmail.com', 'Cappuccino Cafe', 'cappuccinocafe.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('joyindianrestaurant.com@gmail.com', 'Joy Indian Restaurant', 'joyindianrestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('zhotel.com@gmail.com', 'Z Hotel', 'zhotel.com', 'This is the description of this business', 'Florist', 'Pending'),
('sunnyflorists.com@gmail.com', 'Sunny Florists', 'sunnyflorists.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('koelnerbierhalle.com@gmail.com', 'Koelner Bier Halle', 'koelnerbierhalle.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('mapleleafflower.com@gmail.com', 'MapleLeaf Flower', 'mapleleafflower.com', 'This is the description of this business', 'Florist', 'Pending'),
('babybosburritos.com@gmail.com', 'Baby BoS Burritos', 'babybosburritos.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('rose&co.com@gmail.com', 'Rose & Co', 'rose&co.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('kendallflowershop.com@gmail.com', 'Kendall Flower Shop', 'kendallflowershop.com', 'This is the description of this business', 'Florist', 'Pending'),
('nb.nationalbakery.com@gmail.com', 'Nb. National Bakery', 'nb.nationalbakery.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('sscalabropizzeria.com@gmail.com', 'S S Calabro Pizzeria', 'sscalabropizzeria.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('cabana.com@gmail.com', 'Cabana', 'cabana.com', 'This is the description of this business', 'Florist', 'Reported'),
('doubledragonrestaurant.com@gmail.com', 'Double Dragon Restaurant', 'doubledragonrestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('intin.y.c..com@gmail.com', 'Inti N.Y.C.', 'intin.y.c..com', 'This is the description of this business', 'Restaurant', 'Pending'),
('oishiijapansestex-mex.com@gmail.com', 'Oishii Japanses Tex-Mex', 'oishiijapansestex-mex.com', 'This is the description of this business', 'Florist', 'Pending'),
('lapetitebouquet.com@gmail.com', 'La Petite Bouquet', 'lapetitebouquet.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('valianopizza.com@gmail.com', 'Valiano Pizza', 'valianopizza.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('flowersforeveryone.com@gmail.com', 'Flowers For Everyone', 'flowersforeveryone.com', 'This is the description of this business', 'Florist', 'Reported'),
('mediterraneo.com@gmail.com', 'Mediterraneo', 'mediterraneo.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('casanova.com@gmail.com', 'Casa Nova', 'casanova.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('theflyinglobster.com@gmail.com', 'The Flying Lobster', 'theflyinglobster.com', 'This is the description of this business', 'Florist', 'Pending'),
('studebakercafe.com@gmail.com', 'Studebaker Cafe', 'studebakercafe.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('onioncreekflowers.com@gmail.com', 'Onion Creek Flowers', 'onioncreekflowers.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('sagaponack.com@gmail.com', 'Sagaponack', 'sagaponack.com', 'This is the description of this business', 'Florist', 'Accepted'),
('zafisluncheonette.com@gmail.com', 'ZafiS Luncheonette', 'zafisluncheonette.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('flowersforyou.com@gmail.com', 'Flowers For You', 'flowersforyou.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('villaelbacatering.com@gmail.com', 'Villa Elba Catering', 'villaelbacatering.com', 'This is the description of this business', 'Florist', 'Reported'),
('zagarawinebar.com@gmail.com', 'Zagara Wine Bar', 'zagarawinebar.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('barcorvo.com@gmail.com', 'Bar Corvo', 'barcorvo.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('rainbowroom.com@gmail.com', 'Rainbow Room', 'rainbowroom.com', 'This is the description of this business', 'Florist', 'Pending'),
('zablozkis.com@gmail.com', 'Zablozkis', 'zablozkis.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('eddiesheroplace.com@gmail.com', 'Eddies Hero Place', 'eddiesheroplace.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('safra.com@gmail.com', 'Safra', 'safra.com', 'This is the description of this business', 'Florist', 'Accepted'),
('yungsunseafoodrestaurant.com@gmail.com', 'Yung Sun Seafood Restaurant', 'yungsunseafoodrestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('bloomcouture.com@gmail.com', 'Bloom Couture', 'bloomcouture.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('barcentrale.com@gmail.com', 'Bar Centrale', 'barcentrale.com', 'This is the description of this business', 'Florist', 'Accepted'),
('villamarrestaurant.com@gmail.com', 'Villa Mar Restaurant', 'villamarrestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('olgaspizza.com@gmail.com', 'OlgaS Pizza', 'olgaspizza.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('queensconcessionstand.com@gmail.com', 'Queens Concession Stand', 'queensconcessionstand.com', 'This is the description of this business', 'Florist', 'Accepted'),
('bloomex.com@gmail.com', 'Bloomex', 'bloomex.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('milonbangladesh&indianrestaurant.com@gmail.com', 'Milon Bangladesh & Indian Restaurant', 'milonbangladesh&indianrestaurant.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('pacificanarest.com@gmail.com', 'Pacificana Rest', 'pacificanarest.com', 'This is the description of this business', 'Florist', 'Pending'),
('mccoyspub.com@gmail.com', 'MccoyS Pub', 'mccoyspub.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('internationalwingsfactory.com@gmail.com', 'International Wings Factory', 'internationalwingsfactory.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('tacogrill.com@gmail.com', 'Taco Grill', 'tacogrill.com', 'This is the description of this business', 'Florist', 'Reported'),
('pastafinapizza.com@gmail.com', 'Pastafina Pizza', 'pastafinapizza.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('dillingerspub&grill.com@gmail.com', 'Dillingers Pub & Grill', 'dillingerspub&grill.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('arharnthaicuisine.com@gmail.com', 'Arharn Thai Cuisine', 'arharnthaicuisine.com', 'This is the description of this business', 'Florist', 'Pending'),
('nazbakery&rotishop.com@gmail.com', 'Naz Bakery & Roti Shop', 'nazbakery&rotishop.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('capizzi.com@gmail.com', 'Capizzi', 'capizzi.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('zumbarestaurant.com@gmail.com', 'Zumba Restaurant', 'zumbarestaurant.com', 'This is the description of this business', 'Florist', 'Accepted'),
('koftepiyazrestaurant.com@gmail.com', 'Kofte Piyaz Restaurant', 'koftepiyazrestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('villagardenfamouspizza.com@gmail.com', 'Villa Garden Famous Pizza', 'villagardenfamouspizza.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('petesgrill.com@gmail.com', 'PeteS Grill', 'petesgrill.com', 'This is the description of this business', 'Florist', 'Pending'),
('zahlayasbistro.com@gmail.com', 'ZahlayaS Bistro', 'zahlayasbistro.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('laura’sgarden.com@gmail.com', 'Laura’s Garden', 'laura’sgarden.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('artsandcraftsbeerparlor.com@gmail.com', 'Arts And Crafts Beer Parlor', 'artsandcraftsbeerparlor.com', 'This is the description of this business', 'Florist', 'Pending'),
('coleen’sflowershop.com@gmail.com', 'Coleen’s Flower Shop', 'coleen’sflowershop.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('joykitchenchineserestaurant.com@gmail.com', 'Joy Kitchen Chinese Restaurant', 'joykitchenchineserestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('artusopastryshop.com@gmail.com', 'Artuso Pastry Shop', 'artusopastryshop.com', 'This is the description of this business', 'Florist', 'Reported'),
('baked.com@gmail.com', 'Baked', 'baked.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('sarilingatin.com@gmail.com', 'Sariling Atin', 'sarilingatin.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('abetterflorist.com@gmail.com', 'A Better Florist', 'abetterflorist.com', 'This is the description of this business', 'Florist', 'Pending'),
('willisnorthamerica.com@gmail.com', 'Willis North America', 'willisnorthamerica.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('joya.com@gmail.com', 'Joya', 'joya.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('backbayflorist.com@gmail.com', 'Back Bay Florist', 'backbayflorist.com', 'This is the description of this business', 'Florist', 'Reported'),
('fancyflowersandgifts.com@gmail.com', 'Fancy Flowers And Gifts', 'fancyflowersandgifts.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('flowersforher.com@gmail.com', 'Flowers For Her', 'flowersforher.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('mcdonald.com@gmail.com', 'Mcdonald', 'mcdonald.com', 'This is the description of this business', 'Florist', 'Pending'),
('o.m.flowershop.com@gmail.com', 'O.M. Flower Shop', 'o.m.flowershop.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('thainy.com@gmail.com', 'Thainy', 'thainy.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('pacha.com@gmail.com', 'Pacha', 'pacha.com', 'This is the description of this business', 'Florist', 'Accepted'),
('zuccabucafrozenyogurt.com@gmail.com', 'Zucca Buca Frozen Yogurt', 'zuccabucafrozenyogurt.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('jamrock.com@gmail.com', 'Jam Rock', 'jamrock.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('rafaelinarestaurant&barcorp.com@gmail.com', 'Rafaelina Restaurant & Bar Corp', 'rafaelinarestaurant&barcorp.com', 'This is the description of this business', 'Florist', 'Accepted'),
('pinchetaquiera.com@gmail.com', 'Pinche Taquiera', 'pinchetaquiera.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('wolff’sfloraldesigns.com@gmail.com', 'Wolff’s Floral Designs', 'wolff’sfloraldesigns.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('sasabuneexpressnewyork.com@gmail.com', 'Sasabune Express New York', 'sasabuneexpressnewyork.com', 'This is the description of this business', 'Florist', 'Pending'),
('cieloatthemayfair.com@gmail.com', 'Cielo At The Mayfair', 'cieloatthemayfair.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('c&ccatering.com@gmail.com', 'C & C Catering', 'c&ccatering.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('pekingkitchenchinesecuisine.com@gmail.com', 'Peking Kitchen Chinese Cuisine', 'pekingkitchenchinesecuisine.com', 'This is the description of this business', 'Florist', 'Pending'),
('olympiaflowerstore.com@gmail.com', 'Olympia Flower Store', 'olympiaflowerstore.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('tacoexpress.com@gmail.com', 'Taco Express', 'tacoexpress.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('flowerbros.com@gmail.com', 'Flower Bros', 'flowerbros.com', 'This is the description of this business', 'Florist', 'Pending'),
('raffaello.com@gmail.com', 'Raffaello', 'raffaello.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('joygarden.com@gmail.com', 'Joy Garden', 'joygarden.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('townhallflowers.com@gmail.com', 'Town Hall Flowers', 'townhallflowers.com', 'This is the description of this business', 'Florist', 'Pending'),
('xtracheesepizzeria.com@gmail.com', 'Xtra Cheese Pizzeria', 'xtracheesepizzeria.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('villaitaliankitchen.com@gmail.com', 'Villa Italian Kitchen', 'villaitaliankitchen.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('egyptiancoffeeshop.com@gmail.com', 'Egyptian Coffee Shop', 'egyptiancoffeeshop.com', 'This is the description of this business', 'Florist', 'Accepted'),
('barcatalonia.com@gmail.com', 'Bar Catalonia', 'barcatalonia.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('washingtonbagelcafe.com@gmail.com', 'Washington Bagel Cafe', 'washingtonbagelcafe.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('showmanscafe.com@gmail.com', 'ShowmanS Cafe', 'showmanscafe.com', 'This is the description of this business', 'Florist', 'Reported'),
('pacifickitchen.com@gmail.com', 'Pacific Kitchen', 'pacifickitchen.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('umamiburger.com@gmail.com', 'Umami Burger', 'umamiburger.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('pasteskikosnewyork.com@gmail.com', 'Pastes KikoS New York', 'pasteskikosnewyork.com', 'This is the description of this business', 'Florist', 'Pending'),
('shqiperiacafe.com@gmail.com', 'Shqiperia Cafe', 'shqiperiacafe.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('studio151.com@gmail.com', 'Studio 151', 'studio151.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('ohanajapanesehibachiseafood&steak.com@gmail.com', 'Ohana Japanese Hibachi Seafood & Steak', 'ohanajapanesehibachiseafood&steak.com', 'This is the description of this business', 'Florist', 'Reported'),
('dimsumgogo.com@gmail.com', 'Dim Sum Go Go', 'dimsumgogo.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('littlefoxflowers.com@gmail.com', 'Little Fox Flowers', 'littlefoxflowers.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('thaitonys.com@gmail.com', 'Thai TonyS', 'thaitonys.com', 'This is the description of this business', 'Florist', 'Reported'),
('dinodots.com@gmail.com', 'Dino Dots', 'dinodots.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('radiostar.com@gmail.com', 'Radio Star', 'radiostar.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('dino.com@gmail.com', 'Dino', 'dino.com', 'This is the description of this business', 'Florist', 'Accepted'),
('c.m.coffeeshop.com@gmail.com', 'C.M. Coffee Shop', 'c.m.coffeeshop.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('buds2blooms.com@gmail.com', 'Buds 2 Blooms', 'buds2blooms.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('cadwalader,wickersham&taft.com@gmail.com', 'Cadwalader, Wickersham & Taft', 'cadwalader,wickersham&taft.com', 'This is the description of this business', 'Florist', 'Accepted'),
('morningglory.com@gmail.com', 'Morning Glory', 'morningglory.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('nellie’swildflowers.com@gmail.com', 'Nellie’s Wild Flowers', 'nellie’swildflowers.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('babaspierogies.com@gmail.com', 'Babas Pierogies', 'babaspierogies.com', 'This is the description of this business', 'Florist', 'Pending'),
('dinastiachina.com@gmail.com', 'Dinastia China', 'dinastiachina.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('mcdermottspub.com@gmail.com', 'McdermottS Pub', 'mcdermottspub.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('eim.com@gmail.com', 'Eim', 'eim.com', 'This is the description of this business', 'Florist', 'Reported'),
('pinchetaqueria.com@gmail.com', 'Pinche Taqueria', 'pinchetaqueria.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('zabbelee.com@gmail.com', 'Zabb Elee', 'zabbelee.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('blessedstems.com@gmail.com', 'Blessed Stems', 'blessedstems.com', 'This is the description of this business', 'Florist', 'Accepted'),
('zuckersbagelsandsmokedfish.com@gmail.com', 'ZuckerS Bagels And Smoked Fish', 'zuckersbagelsandsmokedfish.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('wilmerhale.com@gmail.com', 'Wilmer Hale', 'wilmerhale.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('pinebar&grill.com@gmail.com', 'Pine Bar & Grill', 'pinebar&grill.com', 'This is the description of this business', 'Florist', 'Accepted'),
('westbankflowermarket.com@gmail.com', 'Westbank Flower Market', 'westbankflowermarket.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('wasabipoint.com@gmail.com', 'Wasabi Point', 'wasabipoint.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('pimentocarribeanrestaurant.com@gmail.com', 'Pimento Carribean Restaurant', 'pimentocarribeanrestaurant.com', 'This is the description of this business', 'Florist', 'Reported'),
('floramor.com@gmail.com', 'Flor Amor', 'floramor.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('oishibaysushirestaurant.com@gmail.com', 'Oishi Baysushi Restaurant', 'oishibaysushirestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('internationalhouse.com@gmail.com', 'Internationalhouse', 'internationalhouse.com', 'This is the description of this business', 'Florist', 'Pending'),
('ironsushi.com@gmail.com', 'Iron Sushi', 'ironsushi.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('umaijapaneserestaurant.com@gmail.com', 'Umai Japanese Restaurant', 'umaijapaneserestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('pachangapatterson.com@gmail.com', 'Pachanga Patterson', 'pachangapatterson.com', 'This is the description of this business', 'Florist', 'Reported'),
('kim’sflowershop.com@gmail.com', 'Kim’s Flower Shop', 'kim’sflowershop.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('koffeecakecorner.com@gmail.com', 'Koffeecake Corner', 'koffeecakecorner.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('raescafe.com@gmail.com', 'RaeS Cafe', 'raescafe.com', 'This is the description of this business', 'Florist', 'Reported'),
('eightturncrepe.com@gmail.com', 'Eight Turn Crepe', 'eightturncrepe.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('jayne’sflowers.com@gmail.com', 'Jayne’s Flowers', 'jayne’sflowers.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('shuhanjuauthenticchinesecuisine.com@gmail.com', 'Shu Han Ju Authentic Chinese Cuisine', 'shuhanjuauthenticchinesecuisine.com', 'This is the description of this business', 'Florist', 'Accepted'),
('zuckerbakery.com@gmail.com', 'Zucker Bakery', 'zuckerbakery.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('pacificmoon.com@gmail.com', 'Pacific Moon', 'pacificmoon.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('henryst.alehouse.com@gmail.com', 'Henry St. Ale House', 'henryst.alehouse.com', 'This is the description of this business', 'Florist', 'Pending'),
('cilantro.com@gmail.com', 'Cilantro', 'cilantro.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('pekingkitchen.com@gmail.com', 'Peking Kitchen', 'pekingkitchen.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('irishrover.com@gmail.com', 'Irish Rover', 'irishrover.com', 'This is the description of this business', 'Florist', 'Accepted'),
('zibettoespressobar.com@gmail.com', 'Zibetto Espresso Bar', 'zibettoespressobar.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('benwhiteflorist.com@gmail.com', 'Ben White Florist', 'benwhiteflorist.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('artofbloomflorist.com@gmail.com', 'Art of Bloom Florist', 'artofbloomflorist.com', 'This is the description of this business', 'Florist', 'Pending'),
('dhel’sflowers.com@gmail.com', 'Dhel’s Flowers', 'dhel’sflowers.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('edenwok.com@gmail.com', 'Eden Wok', 'edenwok.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('pekingkitchenii.com@gmail.com', 'Peking Kitchen Ii', 'pekingkitchenii.com', 'This is the description of this business', 'Florist', 'Pending'),
('sage.com@gmail.com', 'Sage', 'sage.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('piece-a-cakebakery.com@gmail.com', 'Piece-A-Cake Bakery', 'piece-a-cakebakery.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('whitelotusflowers.com@gmail.com', 'White Lotus Flowers', 'whitelotusflowers.com', 'This is the description of this business', 'Florist', 'Reported'),
('blackorchidfloraldesign.com@gmail.com', 'Black Orchid Floral Design', 'blackorchidfloraldesign.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('yogurtinlove.com@gmail.com', 'Yogurt In Love', 'yogurtinlove.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('jack&nellies.com@gmail.com', 'Jack & NellieS', 'jack&nellies.com', 'This is the description of this business', 'Florist', 'Accepted'),
('pastelitoselvys.com@gmail.com', 'Pastelitos Elvys', 'pastelitoselvys.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('valbonarestaurant.com@gmail.com', 'Valbona Restaurant', 'valbonarestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('edibleblooms.com@gmail.com', 'Edible Blooms', 'edibleblooms.com', 'This is the description of this business', 'Florist', 'Reported'),
('irohajapaneserestaurant.com@gmail.com', 'Iroha Japanese Restaurant', 'irohajapaneserestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('zhongwahchineserestaurant.com@gmail.com', 'Zhong Wah Chinese Restaurant', 'zhongwahchineserestaurant.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('arianarestaurant.com@gmail.com', 'Ariana Restaurant', 'arianarestaurant.com', 'This is the description of this business', 'Florist', 'Reported'),
('rosevalley.com@gmail.com', 'Rose Valley', 'rosevalley.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('caterinaspizzeria.com@gmail.com', 'Caterinas Pizzeria', 'caterinaspizzeria.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('sweetheartflorist.com@gmail.com', 'Sweetheart Florist', 'sweetheartflorist.com', 'This is the description of this business', 'Florist', 'Pending'),
('williessteakhouse.com@gmail.com', 'WillieS Steak House', 'williessteakhouse.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('yuvafrontierindiangrill.com@gmail.com', 'Yuva Frontier Indian Grill', 'yuvafrontierindiangrill.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('florista.com@gmail.com', 'Florista', 'florista.com', 'This is the description of this business', 'Florist', 'Reported'),
('petespizza.com@gmail.com', 'PeteS Pizza', 'petespizza.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('millyscornerrestaurantandbar.com@gmail.com', 'MillyS Corner Restaurant And Bar', 'millyscornerrestaurantandbar.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('onda.com@gmail.com', 'Onda', 'onda.com', 'This is the description of this business', 'Florist', 'Reported'),
('sami’sflowershop.com@gmail.com', 'Sami’s Flower Shop', 'sami’sflowershop.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('cienfuegos.com@gmail.com', 'Cien Fuegos', 'cienfuegos.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('winchineserestaurant.com@gmail.com', 'Win Chinese Restaurant', 'winchineserestaurant.com', 'This is the description of this business', 'Florist', 'Reported'),
('barcoastal.com@gmail.com', 'Bar Coastal', 'barcoastal.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('nayamezze&grill.com@gmail.com', 'Naya Mezze & Grill', 'nayamezze&grill.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('petesclamstop.com@gmail.com', 'PeteS Clam Stop', 'petesclamstop.com', 'This is the description of this business', 'Florist', 'Pending'),
('rosebay.com@gmail.com', 'Rose Bay', 'rosebay.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('dingdong.com@gmail.com', 'Ding Dong', 'dingdong.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('eggwell.com@gmail.com', 'Eggwell', 'eggwell.com', 'This is the description of this business', 'Florist', 'Pending'),
('piecorps.com@gmail.com', 'Pie Corps', 'piecorps.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('herbalife.com@gmail.com', 'Herbalife', 'herbalife.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('ukrainianrestaurant.com@gmail.com', 'Ukrainian Restaurant', 'ukrainianrestaurant.com', 'This is the description of this business', 'Florist', 'Pending'),
('bailichineserestaurant.com@gmail.com', 'Bai Li Chinese Restaurant', 'bailichineserestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('mccannspub.com@gmail.com', 'MccannS Pub', 'mccannspub.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('propertyflower.com@gmail.com', 'Property Flower', 'propertyflower.com', 'This is the description of this business', 'Florist', 'Pending'),
('magpieblossomboutique.com@gmail.com', 'Magpie Blossom Boutique', 'magpieblossomboutique.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('shuberttheater.com@gmail.com', 'Shubert Theater', 'shuberttheater.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('barbrace.com@gmail.com', 'Bar Brace', 'barbrace.com', 'This is the description of this business', 'Florist', 'Accepted'),
('shukmediterraneancuisine.com@gmail.com', 'Shuk Mediterranean Cuisine', 'shukmediterraneancuisine.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('wimpysrestaurant.com@gmail.com', 'Wimpys Restaurant', 'wimpysrestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('winhingchineserestaurant.com@gmail.com', 'Win Hing Chinese Restaurant', 'winhingchineserestaurant.com', 'This is the description of this business', 'Florist', 'Reported'),
('kaffe3,inc..com@gmail.com', 'Kaffe 3, Inc.', 'kaffe3,inc..com', 'This is the description of this business', 'Restaurant', 'Pending'),
('hermesbilliards&cafe.com@gmail.com', 'Hermes Billiards & Cafe', 'hermesbilliards&cafe.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('ultimategrill.com@gmail.com', 'Ultimate Grill', 'ultimategrill.com', 'This is the description of this business', 'Florist', 'Reported'),
('looseleaf.com@gmail.com', 'Loose Leaf', 'looseleaf.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('millyspizzeria.com@gmail.com', 'MillyS Pizzeria', 'millyspizzeria.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('dinospizza&pasta.com@gmail.com', 'Dinos Pizza & Pasta', 'dinospizza&pasta.com', 'This is the description of this business', 'Florist', 'Accepted'),
('theflyingpuck.com@gmail.com', 'The Flying Puck', 'theflyingpuck.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('thaivillage.com@gmail.com', 'Thai Village', 'thaivillage.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('j.rscabaret.com@gmail.com', 'J.Rs Cabaret', 'j.rscabaret.com', 'This is the description of this business', 'Florist', 'Accepted'),
('yankarisquaresoul2soul.com@gmail.com', 'Yankari Square Soul 2 Soul', 'yankarisquaresoul2soul.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('louisbarryflorist.com@gmail.com', 'Louis Barry Florist', 'louisbarryflorist.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('valbellamidtown.com@gmail.com', 'Valbella Midtown', 'valbellamidtown.com', 'This is the description of this business', 'Florist', 'Accepted'),
('theflowersocial.com@gmail.com', 'The Flower Social', 'theflowersocial.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('umatemakeria.com@gmail.com', 'Uma Temakeria', 'umatemakeria.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('flowercity.com@gmail.com', 'Flower City', 'flowercity.com', 'This is the description of this business', 'Florist', 'Accepted'),
('hallsoftaraflorist.com@gmail.com', 'Halls of Tara Florist', 'hallsoftaraflorist.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('cabrini181.com@gmail.com', 'Cabrini 181', 'cabrini181.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('baharyfishmarket.com@gmail.com', 'Bahary Fish Market', 'baharyfishmarket.com', 'This is the description of this business', 'Florist', 'Reported'),
('eddiessweetshop.com@gmail.com', 'Eddies Sweet Shop', 'eddiessweetshop.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('baritalia.com@gmail.com', 'Bar Italia', 'baritalia.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('cestboncafe.com@gmail.com', 'Cest Bon Cafe', 'cestboncafe.com', 'This is the description of this business', 'Florist', 'Reported'),
('quentinpizza.com@gmail.com', 'Quentin Pizza', 'quentinpizza.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('ujafederation.com@gmail.com', 'Uja Federation', 'ujafederation.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('stemsfloraldesign.com@gmail.com', 'Stems Floral Design', 'stemsfloraldesign.com', 'This is the description of this business', 'Florist', 'Accepted'),
('thelittleflowershop.com@gmail.com', 'The Little Flower Shop', 'thelittleflowershop.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('flowercreations.com@gmail.com', 'Flower Creations', 'flowercreations.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('argan.com@gmail.com', 'Argan', 'argan.com', 'This is the description of this business', 'Florist', 'Accepted'),
('thaiterminal.com@gmail.com', 'Thai Terminal', 'thaiterminal.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('milosyard.com@gmail.com', 'MiloS Yard', 'milosyard.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('diner.com@gmail.com', 'Diner', 'diner.com', 'This is the description of this business', 'Florist', 'Reported'),
('wasabisushibento.com@gmail.com', 'Wasabi Sushi Bento', 'wasabisushibento.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('cadaques.com@gmail.com', 'Cadaques', 'cadaques.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('eddiejrssportlounge.com@gmail.com', 'Eddie Jrs Sport Lounge', 'eddiejrssportlounge.com', 'This is the description of this business', 'Florist', 'Reported'),
('doubledragonchineserestaurant.com@gmail.com', 'Double Dragon Chinese Restaurant', 'doubledragonchineserestaurant.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('stroni.com@gmail.com', 'Stroni', 'stroni.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('caterinapizza.com@gmail.com', 'Caterina Pizza', 'caterinapizza.com', 'This is the description of this business', 'Florist', 'Accepted'),
('vai.com@gmail.com', 'Vai', 'vai.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('umamishoppu.com@gmail.com', 'Umami Shoppu', 'umamishoppu.com', 'This is the description of this business', 'Restaurant', 'Reported'),
('walton’sfancy&staple.com@gmail.com', 'Walton’s Fancy & Staple', 'walton’sfancy&staple.com', 'This is the description of this business', 'Florist', 'Accepted'),
('sunsetfloral.com@gmail.com', 'Sunset Floral', 'sunsetfloral.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('flowerswithessence.com@gmail.com', 'Flowers With Essence', 'flowerswithessence.com', 'This is the description of this business', 'Restaurant', 'Accepted'),
('oh!bagelcafe.com@gmail.com', 'Oh! Bagel Cafe', 'oh!bagelcafe.com', 'This is the description of this business', 'Florist', 'Accepted'),
('z&cjamaicancuisine.com@gmail.com', 'Z&C Jamaicancuisine', 'z&cjamaicancuisine.com', 'This is the description of this business', 'Restaurant', 'Pending'),
('warrenhallcoffeebar.com@gmail.com', 'Warren Hall Coffee Bar', 'warrenhallcoffeebar.com', 'This is the description of this business', 'Restaurant', 'Accepted');
