version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: proj_demo
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
