INSERT INTO promotion (email,title,description,promotion_code,image_name, clicks) VALUES 
('bythewaybakery.com@gmail.com', 'Promotion of By The Way Bakery', 'Description of the Promotion', '5XvwaGed', 'DEFAULT_F', 427),
('ultimatefitness,queens.com@gmail.com', 'Promotion of Ultimate Fitness, Queens', 'Description of the Promotion', 'Y0utmy7M', 'DEFAULT_R2', 678),
('naturebliss.com@gmail.com', 'Promotion of Nature Bliss', 'Description of the Promotion', 'AghrLGOS', 'DEFAULT_R', 211),
('c-pac/pulse48.com@gmail.com', 'Promotion of C-Pac/Pulse 48', 'Description of the Promotion', '2r4zS8gy', 'DEFAULT_F2', 281),
('willieos.com@gmail.com', 'Promotion of Willie OS', 'Description of the Promotion', '6iQDmbGM', 'DEFAULT_F2', 357),
('herballife/saludesvida.com@gmail.com', 'Promotion of Herbal Life/Salud Es Vida', 'Description of the Promotion', 'waYhfHVu', 'DEFAULT_F', 968),
('kaffekuppen.com@gmail.com', 'Promotion of Kaffe Kuppen', 'Description of the Promotion', 'k6uzCOY8', 'DEFAULT_F', 896),
('shuko.com@gmail.com', 'Promotion of Shuko', 'Description of the Promotion', 'WbQntfpd', 'DEFAULT_F2', 884),
('sagarchinese.com@gmail.com', 'Promotion of Sagar Chinese', 'Description of the Promotion', 'D3CN52FO', 'DEFAULT_F2', 477),
('zhousyummyrestaurant.com@gmail.com', 'Promotion of ZhouS Yummy Restaurant', 'Description of the Promotion', 'Isa8RvhD', 'DEFAULT_R2', 516),
('lakelineflorist&giftsinc.com@gmail.com', 'Promotion of Lakeline Florist & Gifts Inc', 'Description of the Promotion', '68CStHTf', 'DEFAULT_F2', 885),
('cacio&pepe.com@gmail.com', 'Promotion of Cacio & Pepe', 'Description of the Promotion', 'gXdy1lNw', 'DEFAULT_R2', 985),
('ontrackbar(o.t.b.).com@gmail.com', 'Promotion of On Track Bar (O.T.B.)', 'Description of the Promotion', 'aLPES2fA', 'DEFAULT_R2', 718),
('thailandcafe.com@gmail.com', 'Promotion of Thailand Cafe', 'Description of the Promotion', 'OLfdnKFc', 'DEFAULT_F2', 707),
('prince’sflowershop.com@gmail.com', 'Promotion of Prince’s Flower Shop', 'Description of the Promotion', 'r4CBhyvL', 'DEFAULT_R', 639),
('aryakabobhouse.com@gmail.com', 'Promotion of Arya Kabob House', 'Description of the Promotion', 'qe6PAwZS', 'DEFAULT_R2', 597),
('shortys.com@gmail.com', 'Promotion of ShortyS', 'Description of the Promotion', 'JufY8zM6', 'DEFAULT_R', 953),
('metropolitan.com@gmail.com', 'Promotion of Metropolitan', 'Description of the Promotion', '8UtHbFaS', 'DEFAULT_F2', 959),
('nublu.com@gmail.com', 'Promotion of Nublu', 'Description of the Promotion', 'VdCmy1Qi', 'DEFAULT_F2', 929),
('doubledragon.com@gmail.com', 'Promotion of Double Dragon', 'Description of the Promotion', 'Y9lxWe1c', 'DEFAULT_F2', 313),
('dreamevents.com@gmail.com', 'Promotion of Dream Events', 'Description of the Promotion', 'rVGFNsic', 'DEFAULT_F2', 229),
('yangshappygarden.com@gmail.com', 'Promotion of YangS Happy Garden', 'Description of the Promotion', 'fzmTkK47', 'DEFAULT_F2', 917),
('paradisemanor.com@gmail.com', 'Promotion of Paradise Manor', 'Description of the Promotion', 'fDjSKxHZ', 'DEFAULT_R2', 402),
('pacinispizzeria.com@gmail.com', 'Promotion of PaciniS Pizzeria', 'Description of the Promotion', 'LVGWmhRK', 'DEFAULT_F2', 204),
('yvonneyvonnerestaurant.com@gmail.com', 'Promotion of Yvonne Yvonne Restaurant', 'Description of the Promotion', 'aT4yRDlv', 'DEFAULT_F', 522),
('jameswhite&sons.com@gmail.com', 'Promotion of James White & Sons', 'Description of the Promotion', 'tFr2RAp7', 'DEFAULT_F2', 200),
('yangsgoodtaste.com@gmail.com', 'Promotion of YangS Good Taste', 'Description of the Promotion', 'ljKYudqr', 'DEFAULT_R2', 383),
('caborestaurant.com@gmail.com', 'Promotion of Cabo Restaurant', 'Description of the Promotion', 'PVO4IHNm', 'DEFAULT_F2', 304),
('yankeebar&grill.com@gmail.com', 'Promotion of Yankee Bar & Grill', 'Description of the Promotion', 'yM8dRpus', 'DEFAULT_R2', 329),
('chabaflorists.com@gmail.com', 'Promotion of Chaba Florists', 'Description of the Promotion', 'MeFST5O9', 'DEFAULT_F', 545),
('24hourflowers.com@gmail.com', 'Promotion of 24 Hour Flowers', 'Description of the Promotion', '4GWudvf5', 'DEFAULT_R', 271),
('vallspizzeria.com@gmail.com', 'Promotion of VallS Pizzeria', 'Description of the Promotion', 'ahTVwRnG', 'DEFAULT_F', 689),
('medusa.com@gmail.com', 'Promotion of Medusa', 'Description of the Promotion', 'MJqemu6o', 'DEFAULT_R', 699),
('bainbridgebakery.com@gmail.com', 'Promotion of Bainbridge Bakery', 'Description of the Promotion', 'QuhSI3k9', 'DEFAULT_R2', 370),
('queenscomfortrestaurant.com@gmail.com', 'Promotion of Queens Comfort Restaurant', 'Description of the Promotion', 'pDSo97Nn', 'DEFAULT_R', 796),
('bricolagecuratedflorals.com@gmail.com', 'Promotion of Bricolage Curated Florals', 'Description of the Promotion', 'nkgA6uRx', 'DEFAULT_F', 384),
('barbolonat.com@gmail.com', 'Promotion of Bar Bolonat', 'Description of the Promotion', 'xLFYpnel', 'DEFAULT_R', 769),
('cafesicily.com@gmail.com', 'Promotion of Cafe  Sicily', 'Description of the Promotion', 'JZ2Lv6Uw', 'DEFAULT_R', 713),
('thefloraldecorator.com@gmail.com', 'Promotion of The Floral Decorator', 'Description of the Promotion', 'S0Quyqln', 'DEFAULT_F', 616),
('villafiorita.com@gmail.com', 'Promotion of Villa Fiorita', 'Description of the Promotion', '0Xho8rNm', 'DEFAULT_F2', 264),
('bargreatharry.com@gmail.com', 'Promotion of Bar Great Harry', 'Description of the Promotion', 'aNOYPTEL', 'DEFAULT_F2', 795),
('radiocitypizza.com@gmail.com', 'Promotion of Radio City Pizza', 'Description of the Promotion', 'LdH92WQq', 'DEFAULT_R', 902),
('onassiscafe.com@gmail.com', 'Promotion of Onassis Cafe', 'Description of the Promotion', '2sh7uBv9', 'DEFAULT_R', 985),
('ohlala!crepes,inc.com@gmail.com', 'Promotion of Oh Lala! Crepes, Inc', 'Description of the Promotion', 'KxQv2UJA', 'DEFAULT_R', 321),
('babel.com@gmail.com', 'Promotion of Babel', 'Description of the Promotion', '7NAdEUnq', 'DEFAULT_F2', 684),
('charlotte’sfiestaflowers.com@gmail.com', 'Promotion of Charlotte’s Fiesta Flowers', 'Description of the Promotion', 'G8sSuxcz', 'DEFAULT_F2', 259),
('nucafe47.com@gmail.com', 'Promotion of Nu Cafe 47', 'Description of the Promotion', 'PemoRtUs', 'DEFAULT_R2', 738),
('barchuko.com@gmail.com', 'Promotion of Bar Chuko', 'Description of the Promotion', 'xGjYVC64', 'DEFAULT_R', 272),
('shuka.com@gmail.com', 'Promotion of Shuka', 'Description of the Promotion', 'GlMinr1F', 'DEFAULT_F', 221),
('bostoncityflorist.com@gmail.com', 'Promotion of Boston City Florist', 'Description of the Promotion', 'NFRXTgl6', 'DEFAULT_R', 499),
('sagarrestaurant.com@gmail.com', 'Promotion of Sagar Restaurant', 'Description of the Promotion', 'uOkAMPdv', 'DEFAULT_F', 686),
('villafreshitaliankitchen.com@gmail.com', 'Promotion of Villa Fresh Italian Kitchen', 'Description of the Promotion', 'wNoZVQXt', 'DEFAULT_F', 647),
('metromart.com@gmail.com', 'Promotion of Metro Mart', 'Description of the Promotion', 'gYuFAVch', 'DEFAULT_F2', 249),
('catfish.com@gmail.com', 'Promotion of Catfish', 'Description of the Promotion', 'ibWVmvB2', 'DEFAULT_F', 711),
('henry.com@gmail.com', 'Promotion of Henry', 'Description of the Promotion', 'quJBj3gc', 'DEFAULT_F2', 549),
('charleston.com@gmail.com', 'Promotion of Charleston', 'Description of the Promotion', 'TtqEhoCz', 'DEFAULT_F', 838),
('joysiangrestaurant.com@gmail.com', 'Promotion of Joy Siang Restaurant', 'Description of the Promotion', 'hdJ7oiTj', 'DEFAULT_R2', 950),
('wasabirestaurant.com@gmail.com', 'Promotion of Wasabi Restaurant', 'Description of the Promotion', 'O8MHiwPW', 'DEFAULT_F', 510),
('cafe1ofakind.com@gmail.com', 'Promotion of Cafe 1 Of A Kind', 'Description of the Promotion', 'FihQkAIJ', 'DEFAULT_R2', 661),
('zumschneider.com@gmail.com', 'Promotion of Zum Schneider', 'Description of the Promotion', 'HdsfKPJL', 'DEFAULT_F', 355),
('mccormickschmickseafoodrestaurant.com@gmail.com', 'Promotion of Mccormick Schmick Seafood Restaurant', 'Description of the Promotion', 'bCNP6ORt', 'DEFAULT_F', 274),
('shotsbilliards.com@gmail.com', 'Promotion of Shots Billiards', 'Description of the Promotion', 'uSsrUONL', 'DEFAULT_F', 607),
('flowervision.com@gmail.com', 'Promotion of Flower Vision', 'Description of the Promotion', 'SEPdotk8', 'DEFAULT_R2', 895),
('passionbouquetinc.com@gmail.com', 'Promotion of Passion Bouquet Inc', 'Description of the Promotion', 'NCezV3wx', 'DEFAULT_F', 996),
('sarkujapan.com@gmail.com', 'Promotion of Sarku Japan', 'Description of the Promotion', 'EbGiDSnj', 'DEFAULT_F', 284),
('freytag’sflorist.com@gmail.com', 'Promotion of Freytag’s Florist', 'Description of the Promotion', 'JIL7oAF5', 'DEFAULT_R', 594),
('bajancafe.com@gmail.com', 'Promotion of Bajan Cafe', 'Description of the Promotion', 'DsLeUzBv', 'DEFAULT_F', 370),
('strongplace.com@gmail.com', 'Promotion of Strong Place', 'Description of the Promotion', 'mvw1QKbz', 'DEFAULT_R2', 769),
('washingtoncommons.com@gmail.com', 'Promotion of Washington Commons', 'Description of the Promotion', 'Un0KhGVN', 'DEFAULT_F2', 923),
('diana’sflowershop.com@gmail.com', 'Promotion of Diana’s Flower Shop', 'Description of the Promotion', 'UPdoARgC', 'DEFAULT_R', 895),
('yogirestaurant.com@gmail.com', 'Promotion of Yogi Restaurant', 'Description of the Promotion', 'jkoVOsL4', 'DEFAULT_R', 361),
('henrypublic.com@gmail.com', 'Promotion of Henry Public', 'Description of the Promotion', 'QjaMbNX4', 'DEFAULT_R', 821),
('oliengthairestaurant.com@gmail.com', 'Promotion of Olieng Thai Restaurant', 'Description of the Promotion', 'xY902HWj', 'DEFAULT_R2', 519),
('dipdip.com@gmail.com', 'Promotion of Dip Dip', 'Description of the Promotion', '6uRkF4Oe', 'DEFAULT_R2', 381),
('darlingbuds.com@gmail.com', 'Promotion of Darling Buds', 'Description of the Promotion', 'kWjsSEwe', 'DEFAULT_R2', 549),
('nuhotel.com@gmail.com', 'Promotion of Nu Hotel', 'Description of the Promotion', 'jJqVOfxm', 'DEFAULT_R', 283),
('xunsu.com@gmail.com', 'Promotion of Xun Su', 'Description of the Promotion', 'lRN8gAkW', 'DEFAULT_R2', 455),
('raesdeli.com@gmail.com', 'Promotion of RaeS Deli', 'Description of the Promotion', '4Iz618M0', 'DEFAULT_R', 527),
('dinosaurbar-b-que.com@gmail.com', 'Promotion of Dinosaur Bar-B-Que', 'Description of the Promotion', 'FkHMj8Ag', 'DEFAULT_F', 201),
('pasteurgrill&noodles.com@gmail.com', 'Promotion of Pasteur Grill & Noodles', 'Description of the Promotion', 'jhqUaXJB', 'DEFAULT_R', 463),
('buds&bowers.com@gmail.com', 'Promotion of buds&bowers', 'Description of the Promotion', 'sACHQd1w', 'DEFAULT_F2', 730),
('dinarataatandazwallstreethotel.com@gmail.com', 'Promotion of Dina Rata At Andaz Wall Street Hotel', 'Description of the Promotion', 'ZSsjLokY', 'DEFAULT_F2', 965),
('fernbybostonroseflorist.com@gmail.com', 'Promotion of Fern by Boston Rose Florist', 'Description of the Promotion', 'vINHklRc', 'DEFAULT_F', 962),
('wingsflowerexchange.com@gmail.com', 'Promotion of Wings Flower Exchange', 'Description of the Promotion', 'eNIbqjBT', 'DEFAULT_R2', 874),
('pekingoishi.com@gmail.com', 'Promotion of Peking Oishi', 'Description of the Promotion', '5yoTRqMu', 'DEFAULT_R2', 685),
('pastafina.com@gmail.com', 'Promotion of Pastafina', 'Description of the Promotion', 'NWdEazJy', 'DEFAULT_R2', 548),
('valhalla.com@gmail.com', 'Promotion of Valhalla', 'Description of the Promotion', 'fxbajPSq', 'DEFAULT_F', 469),
('poet’sgarden.com@gmail.com', 'Promotion of Poet’s Garden', 'Description of the Promotion', 'BOsxr0on', 'DEFAULT_R', 592),
('capponessalumeria.com@gmail.com', 'Promotion of Cappones Salumeria', 'Description of the Promotion', 'mAgKU7DP', 'DEFAULT_F', 493),
('ko-sushijapaneserestaurant.com@gmail.com', 'Promotion of Ko-Sushi Japanese Restaurant', 'Description of the Promotion', 'Hwuf0AD4', 'DEFAULT_F2', 873),
('kodamasushi.com@gmail.com', 'Promotion of Kodama Sushi', 'Description of the Promotion', 'jd6QlRSw', 'DEFAULT_R2', 820),
('thailandrestaurant.com@gmail.com', 'Promotion of Thailand Restaurant', 'Description of the Promotion', 'GKsqi7uY', 'DEFAULT_R', 751),
('nayaexpress.com@gmail.com', 'Promotion of Naya Express', 'Description of the Promotion', 'JoMD8y71', 'DEFAULT_F2', 355),
('paradisevenusrestaurant.com@gmail.com', 'Promotion of Paradise Venus Restaurant', 'Description of the Promotion', '3BoDyRNW', 'DEFAULT_R', 750),
('arepaspuesmixtas.com@gmail.com', 'Promotion of Arepas Pues Mixtas', 'Description of the Promotion', 'xeDZUfWr', 'DEFAULT_F2', 984),
('cafe101.com@gmail.com', 'Promotion of Cafe 101', 'Description of the Promotion', 'gGfiP016', 'DEFAULT_F', 585),
('argotea.com@gmail.com', 'Promotion of Argotea', 'Description of the Promotion', 'pXE5fwF3', 'DEFAULT_F2', 254),
('pacificstandard.com@gmail.com', 'Promotion of Pacific Standard', 'Description of the Promotion', 'Y7gotGQz', 'DEFAULT_F2', 831),
('arturos.com@gmail.com', 'Promotion of Arturos', 'Description of the Promotion', '8p4eoKqs', 'DEFAULT_F2', 435),
('flowersvassette.com@gmail.com', 'Promotion of Flowers Vassette', 'Description of the Promotion', 'LW7CFOpg', 'DEFAULT_F2', 556),
('j4hookahlounge.com@gmail.com', 'Promotion of J4 Hookah Lounge', 'Description of the Promotion', 'hWZzpUY2', 'DEFAULT_R', 873),
('zuckersbagel.com@gmail.com', 'Promotion of ZuckerS Bagel', 'Description of the Promotion', 'BtCcoxie', 'DEFAULT_R', 830),
('kafeneo.com@gmail.com', 'Promotion of Kafeneo', 'Description of the Promotion', 'TRfokNPI', 'DEFAULT_F2', 972),
('umas.com@gmail.com', 'Promotion of UmaS', 'Description of the Promotion', 'trQPKEak', 'DEFAULT_R2', 764),
('zimebistro.com@gmail.com', 'Promotion of Zime Bistro', 'Description of the Promotion', 'I2qJ1OaT', 'DEFAULT_R', 611),
('jamaicagrillrestaurant.com@gmail.com', 'Promotion of Jamaica Grill Restaurant', 'Description of the Promotion', 'cGw3fJv9', 'DEFAULT_R', 419),
('lotusdesigns.com@gmail.com', 'Promotion of Lotus Designs', 'Description of the Promotion', 'tVL8AMHa', 'DEFAULT_F', 633),
('table&tulip.com@gmail.com', 'Promotion of Table & Tulip', 'Description of the Promotion', 'LOF4Xvqt', 'DEFAULT_F', 710),
('yogomonster.com@gmail.com', 'Promotion of Yogo Monster', 'Description of the Promotion', 'kJNGFvdy', 'DEFAULT_F2', 312),
('proflowers.com@gmail.com', 'Promotion of ProFlowers', 'Description of the Promotion', 'alON7zcM', 'DEFAULT_R2', 817),
('cjbanquetlatino.com@gmail.com', 'Promotion of C J Banquet Latino', 'Description of the Promotion', 'TdRaroyx', 'DEFAULT_R2', 887),
('nuchas.com@gmail.com', 'Promotion of Nuchas', 'Description of the Promotion', '42BcGSxm', 'DEFAULT_F', 588),
('argotea.com@gmail.com', 'Promotion of Argo Tea', 'Description of the Promotion', '1nZ8J0vS', 'DEFAULT_R', 713),
('artofbloom.com@gmail.com', 'Promotion of Art of Bloom', 'Description of the Promotion', 'C1LwlxzP', 'DEFAULT_F', 566),
('navy.com@gmail.com', 'Promotion of Navy', 'Description of the Promotion', 'lNF6AW3D', 'DEFAULT_R', 316),
('intotea.com@gmail.com', 'Promotion of Intotea', 'Description of the Promotion', 'izEqSOAr', 'DEFAULT_R2', 350),
('z-twodiner&lounge.com@gmail.com', 'Promotion of Z-Two Diner & Lounge', 'Description of the Promotion', '10kUHnW5', 'DEFAULT_R2', 443),
('nuccis.com@gmail.com', 'Promotion of Nuccis', 'Description of the Promotion', '9vGwBCxO', 'DEFAULT_R2', 261),
('passionposies.com@gmail.com', 'Promotion of Passion Posies', 'Description of the Promotion', 'J31Ejr5K', 'DEFAULT_R2', 264),
('edamamacutecutsandmore.com@gmail.com', 'Promotion of Edamama Cute Cuts And More', 'Description of the Promotion', 'NDYWehCm', 'DEFAULT_F', 430),
('yogurtdownunder.com@gmail.com', 'Promotion of Yogurt Down Under', 'Description of the Promotion', 'IjZliWSJ', 'DEFAULT_F2', 674),
('bajafresh.com@gmail.com', 'Promotion of Baja Fresh', 'Description of the Promotion', 'jWSM9P6a', 'DEFAULT_F2', 655),
('mccoy.com@gmail.com', 'Promotion of Mccoy', 'Description of the Promotion', 'hKryWadv', 'DEFAULT_R', 243),
('bait&hook.com@gmail.com', 'Promotion of Bait & Hook', 'Description of the Promotion', 'LkoSxqYX', 'DEFAULT_F', 384),
('barcyrknyc.com@gmail.com', 'Promotion of Bar Cyrk Nyc', 'Description of the Promotion', 'c4VLGdDF', 'DEFAULT_F2', 517),
('metrosushicafe.com@gmail.com', 'Promotion of Metro Sushi Cafe', 'Description of the Promotion', 'Xj61r5Gs', 'DEFAULT_F2', 432),
('articulturedesigns.com@gmail.com', 'Promotion of Articulture Designs', 'Description of the Promotion', 'sf8VqUiW', 'DEFAULT_F', 287),
('zaghloulgrill.com@gmail.com', 'Promotion of Zaghloul Grill', 'Description of the Promotion', 'gHyLmhqU', 'DEFAULT_R2', 353),
('flowersarehappy.com@gmail.com', 'Promotion of Flowers Are Happy', 'Description of the Promotion', 'YoRmiDKn', 'DEFAULT_F2', 674),
('ukuscafe.com@gmail.com', 'Promotion of Ukus Cafe', 'Description of the Promotion', 'gIDuvTKA', 'DEFAULT_R2', 900),
('flowerfilter.com@gmail.com', 'Promotion of Flower Filter', 'Description of the Promotion', 'Rcwovp8B', 'DEFAULT_F', 296),
('dimes.com@gmail.com', 'Promotion of Dimes', 'Description of the Promotion', 'nCAoKprP', 'DEFAULT_R2', 700),
('onceuponatart.com@gmail.com', 'Promotion of Once Upon A Tart', 'Description of the Promotion', 's6FMRSzQ', 'DEFAULT_R2', 884),
('cieloristorante.com@gmail.com', 'Promotion of Cielo Ristorante', 'Description of the Promotion', '65olkfYE', 'DEFAULT_F2', 492),
('kaffe1668.com@gmail.com', 'Promotion of Kaffe 1668', 'Description of the Promotion', 'IpU1HQWn', 'DEFAULT_F2', 283),
('willowroad.com@gmail.com', 'Promotion of Willow Road', 'Description of the Promotion', 'FNowKjfC', 'DEFAULT_R2', 975),
('henryslocal.com@gmail.com', 'Promotion of Henrys Local', 'Description of the Promotion', 'VGp0tvbg', 'DEFAULT_F', 461),
('henrysexpresscoffeeshop.com@gmail.com', 'Promotion of Henrys Express Coffee Shop', 'Description of the Promotion', 'YKEUahWr', 'DEFAULT_F', 637),
('studio.com@gmail.com', 'Promotion of Studio', 'Description of the Promotion', '8xfNJa1h', 'DEFAULT_R2', 877),
('zabbcity.com@gmail.com', 'Promotion of Zabb City', 'Description of the Promotion', '6HU4x9i3', 'DEFAULT_F', 634),
('oishisushi.com@gmail.com', 'Promotion of Oishi Sushi', 'Description of the Promotion', 'X8lBR2n3', 'DEFAULT_R2', 637),
('pimpollo.com@gmail.com', 'Promotion of Pimpollo', 'Description of the Promotion', 'L3aWbw1E', 'DEFAULT_R', 798),
('theflowerbucket.com@gmail.com', 'Promotion of The Flower Bucket', 'Description of the Promotion', 'WIj9TxGw', 'DEFAULT_R', 408),
('shrine/yatenga.com@gmail.com', 'Promotion of Shrine/Yatenga', 'Description of the Promotion', 'SxPaZBie', 'DEFAULT_R2', 683),
('xpresspizzeria.com@gmail.com', 'Promotion of Xpress Pizzeria', 'Description of the Promotion', 'KyVv07Lx', 'DEFAULT_R2', 209),
('argoteacafe.com@gmail.com', 'Promotion of Argo Tea Cafe', 'Description of the Promotion', 'GqHS5UvM', 'DEFAULT_R', 627),
('wimpysrestaurant5.com@gmail.com', 'Promotion of WimpyS Restaurant 5', 'Description of the Promotion', 'A6v5q2RZ', 'DEFAULT_F2', 986),
('zuccheroepomodori.com@gmail.com', 'Promotion of Zucchero E Pomodori', 'Description of the Promotion', 'ItPpjWMh', 'DEFAULT_R2', 644),
('eddiefancyfood.com@gmail.com', 'Promotion of Eddie Fancy Food', 'Description of the Promotion', 'P6NWmkiv', 'DEFAULT_R', 810),
('caterinaspizza.com@gmail.com', 'Promotion of Caterinas Pizza', 'Description of the Promotion', 'mHcWUgDk', 'DEFAULT_R2', 324),
('exoticflowers.com@gmail.com', 'Promotion of Exotic Flowers', 'Description of the Promotion', 'O3vCuIJE', 'DEFAULT_R2', 967),
('nbaemployercafeteria.com@gmail.com', 'Promotion of Nba Employer Cafeteria', 'Description of the Promotion', 'P6ajfLWr', 'DEFAULT_R', 773),
('henricasrestaurant.com@gmail.com', 'Promotion of Henricas Restaurant', 'Description of the Promotion', 'qj2PmwRH', 'DEFAULT_F', 235),
('openlotusgarden.com@gmail.com', 'Promotion of Open Lotus Garden', 'Description of the Promotion', '5IWP32dj', 'DEFAULT_R2', 805),
('wildlotus.com@gmail.com', 'Promotion of Wild Lotus', 'Description of the Promotion', 'sFHiv7Zr', 'DEFAULT_F', 408),
('yogurtlacrepe.com@gmail.com', 'Promotion of Yogurt La Crepe', 'Description of the Promotion', 'JcRpVS1d', 'DEFAULT_F2', 601),
('8petals.com@gmail.com', 'Promotion of 8 Petals', 'Description of the Promotion', 'igk01e2K', 'DEFAULT_R2', 274),
('nusushi.com@gmail.com', 'Promotion of Nu Sushi', 'Description of the Promotion', 'YLH5xGZw', 'DEFAULT_F', 355),
('kobesushi.com@gmail.com', 'Promotion of Kobe Sushi', 'Description of the Promotion', 'JvKilEUC', 'DEFAULT_R', 204),
('byungchunsoondae.com@gmail.com', 'Promotion of Byung Chun Soon Dae', 'Description of the Promotion', 'yWEgPzoS', 'DEFAULT_F2', 365),
('caeldonia.com@gmail.com', 'Promotion of Caeldonia', 'Description of the Promotion', 'A3kIw6GJ', 'DEFAULT_F2', 401),
('zhongzheng26restaurantinc.com@gmail.com', 'Promotion of Zhong Zheng 26 Restaurant Inc', 'Description of the Promotion', 'ELx3M64T', 'DEFAULT_R2', 439),
('texasbloomsandgifts.com@gmail.com', 'Promotion of Texas Blooms and Gifts', 'Description of the Promotion', 'AfN1ybWw', 'DEFAULT_R', 535),
('koi.com@gmail.com', 'Promotion of Koi', 'Description of the Promotion', 'ynUWuZ0b', 'DEFAULT_R', 270),
('raffles.com@gmail.com', 'Promotion of Raffles', 'Description of the Promotion', '8H3D0EUA', 'DEFAULT_R2', 625),
('joyiikitchen.com@gmail.com', 'Promotion of Joy Ii Kitchen', 'Description of the Promotion', 'FIgdaisR', 'DEFAULT_R2', 713),
('wasabi.com@gmail.com', 'Promotion of Wasabi', 'Description of the Promotion', 'yXvduKq4', 'DEFAULT_F', 290),
('thalassa.com@gmail.com', 'Promotion of Thalassa', 'Description of the Promotion', '4kfn9EVz', 'DEFAULT_F2', 255),
('glassflower.com@gmail.com', 'Promotion of Glass Flower', 'Description of the Promotion', 'u1zRV8pv', 'DEFAULT_R2', 751),
('caesarspalace.com@gmail.com', 'Promotion of Caesars Palace', 'Description of the Promotion', 'mV9ZKpBj', 'DEFAULT_F', 551),
('bzgrill.com@gmail.com', 'Promotion of Bz Grill', 'Description of the Promotion', 'HtksMPmi', 'DEFAULT_R', 534),
('lonestarbloom.com@gmail.com', 'Promotion of Lone Star Bloom', 'Description of the Promotion', '7LGAmuvM', 'DEFAULT_F2', 435),
('irishpunt.com@gmail.com', 'Promotion of Irish Punt', 'Description of the Promotion', 'a1oFCfI6', 'DEFAULT_R2', 222),
('oligarch.com@gmail.com', 'Promotion of Oligarch', 'Description of the Promotion', 'QS1d8BzL', 'DEFAULT_F', 904),
('sataymalaysian.com@gmail.com', 'Promotion of Satay Malaysian', 'Description of the Promotion', 'yvOraI2T', 'DEFAULT_R2', 579),
('valbellan.y..com@gmail.com', 'Promotion of Valbella N.Y.', 'Description of the Promotion', 'YhRd3DoM', 'DEFAULT_F', 647),
('c2cafe.com@gmail.com', 'Promotion of C2 Cafe', 'Description of the Promotion', 'U6Y7wlLq', 'DEFAULT_F2', 990),
('cabareteseafood.com@gmail.com', 'Promotion of Cabarete Seafood', 'Description of the Promotion', '5E79v3Gs', 'DEFAULT_F', 940),
('always&foreverflorist.com@gmail.com', 'Promotion of Always & Forever Florist', 'Description of the Promotion', 'DZuXBYea', 'DEFAULT_F2', 801),
('millstavern.com@gmail.com', 'Promotion of Mills Tavern', 'Description of the Promotion', 'YrkJLOph', 'DEFAULT_R2', 406),
('enchantedflorist.com@gmail.com', 'Promotion of Enchanted Florist', 'Description of the Promotion', 'QhebDrSF', 'DEFAULT_R2', 792),
('eddyseats.com@gmail.com', 'Promotion of Eddys Eats', 'Description of the Promotion', 'OxSnbhXj', 'DEFAULT_R', 671),
('vamos.com@gmail.com', 'Promotion of Vamos', 'Description of the Promotion', 'rft0JDuL', 'DEFAULT_F2', 785),
('villacastillorestaurantcorp.com@gmail.com', 'Promotion of Villa Castillo Restaurant Corp', 'Description of the Promotion', 'Wu8mBAFa', 'DEFAULT_R2', 277),
('baileyscornerpub.com@gmail.com', 'Promotion of Baileys Corner Pub', 'Description of the Promotion', 'LQK7zFWn', 'DEFAULT_R', 473),
('flowerfolk.com@gmail.com', 'Promotion of Flower Folk', 'Description of the Promotion', 'g9tn6aDJ', 'DEFAULT_R', 890),
('paradorcaleno.com@gmail.com', 'Promotion of Parador Caleno', 'Description of the Promotion', 'WAUzXONF', 'DEFAULT_R2', 537),
('arturospizza.com@gmail.com', 'Promotion of Arturos Pizza', 'Description of the Promotion', 'pH4aD39n', 'DEFAULT_R', 630),
('kahluascafe&restaurant.com@gmail.com', 'Promotion of KahluaS Cafe & Restaurant', 'Description of the Promotion', '98q7ZKGw', 'DEFAULT_R', 522),
('glowingflowers.com@gmail.com', 'Promotion of Glowing Flowers', 'Description of the Promotion', 'WItBMU5X', 'DEFAULT_R', 440),
('thornyroses.com@gmail.com', 'Promotion of Thorny Roses', 'Description of the Promotion', '0ZaMEy7r', 'DEFAULT_F2', 214),
('petals&leaves.com@gmail.com', 'Promotion of Petals & Leaves', 'Description of the Promotion', 'eY5GA2po', 'DEFAULT_R', 635),
('nuccissouth.com@gmail.com', 'Promotion of NucciS South', 'Description of the Promotion', 'FTh5mfZI', 'DEFAULT_F2', 953),
('arianadeli.com@gmail.com', 'Promotion of Ariana Deli', 'Description of the Promotion', 'Ve8kytY6', 'DEFAULT_R2', 788),
('flowermaximum.com@gmail.com', 'Promotion of Flower Maximum', 'Description of the Promotion', 'zJilFjbk', 'DEFAULT_F2', 721),
('diningroom.com@gmail.com', 'Promotion of Dining Room', 'Description of the Promotion', 'XGEk3P8J', 'DEFAULT_R', 849),
('blossom&bows.com@gmail.com', 'Promotion of Blossom & Bows', 'Description of the Promotion', 'LOIvQk4F', 'DEFAULT_F2', 291),
('miloscafe.com@gmail.com', 'Promotion of Milos Cafe', 'Description of the Promotion', 'r9yWL8CR', 'DEFAULT_R2', 503),
('mccanncafeteria.com@gmail.com', 'Promotion of Mccann Cafeteria', 'Description of the Promotion', '3WUlvgie', 'DEFAULT_F', 752),
('irvingglickfloristshop.com@gmail.com', 'Promotion of Irving Glick Florist Shop', 'Description of the Promotion', 'xgwQVm41', 'DEFAULT_F', 622),
('edslobsterbar.com@gmail.com', 'Promotion of Eds Lobster Bar', 'Description of the Promotion', 'nRzyN4vl', 'DEFAULT_R', 807),
('windfall.com@gmail.com', 'Promotion of Windfall', 'Description of the Promotion', 'dnaCQusD', 'DEFAULT_F2', 741),
('bahrche.com@gmail.com', 'Promotion of Bahr Che', 'Description of the Promotion', 'JO6mgILZ', 'DEFAULT_R2', 656),
('yunnankitchen.com@gmail.com', 'Promotion of Yunnan Kitchen', 'Description of the Promotion', 'UBQdD1Gr', 'DEFAULT_R', 647),
('cielocafe.com@gmail.com', 'Promotion of Cielo Cafe', 'Description of the Promotion', 'f1WcSjAx', 'DEFAULT_R2', 709),
('aflowerjunction.com@gmail.com', 'Promotion of A Flower Junction', 'Description of the Promotion', 'JMeqC4QX', 'DEFAULT_R', 637),
('petalmetsugar.com@gmail.com', 'Promotion of Petal Met Sugar', 'Description of the Promotion', 'fdPLOv9V', 'DEFAULT_R2', 266),
('zumajapaneserestaurantnewyork.com@gmail.com', 'Promotion of Zuma Japanese Restaurant New York', 'Description of the Promotion', 'XGs8FUjz', 'DEFAULT_F2', 375),
('strombolipizza.com@gmail.com', 'Promotion of Stromboli Pizza', 'Description of the Promotion', 'FN2PX4CJ', 'DEFAULT_R2', 592),
('tulipanna.com@gmail.com', 'Promotion of Tulipanna', 'Description of the Promotion', '1ORGCo4Y', 'DEFAULT_R', 793),
('robin’sflowershop.com@gmail.com', 'Promotion of Robin’s Flower Shop', 'Description of the Promotion', 'JngEmCh8', 'DEFAULT_R2', 379),
('nsefiftysix.com@gmail.com', 'Promotion of Nse Fifty Six', 'Description of the Promotion', 'WI90HmMG', 'DEFAULT_F', 649),
('milliondeli.com@gmail.com', 'Promotion of Million Deli', 'Description of the Promotion', 'xkcdbZS9', 'DEFAULT_F', 426),
('pieface.com@gmail.com', 'Promotion of Pie Face', 'Description of the Promotion', 'uHp7VmR2', 'DEFAULT_R', 820),
('pinchfooddesign.com@gmail.com', 'Promotion of Pinch Food Design', 'Description of the Promotion', 'HhrnoPKe', 'DEFAULT_F2', 767),
('mondayblooms.com@gmail.com', 'Promotion of Monday Blooms', 'Description of the Promotion', 'H5xWf0hK', 'DEFAULT_R', 524),
('happybirthdayflowers.com@gmail.com', 'Promotion of Happy Birthday Flowers', 'Description of the Promotion', '7fK6WuHN', 'DEFAULT_R2', 977),
('ohtaisho.com@gmail.com', 'Promotion of Oh Taisho', 'Description of the Promotion', 'EAoW7BKz', 'DEFAULT_R', 829),
('mercedesflowers.com@gmail.com', 'Promotion of Mercedes Flowers', 'Description of the Promotion', 'jwtu1LeC', 'DEFAULT_F', 879),
('yogurt&company.com@gmail.com', 'Promotion of Yogurt & Company', 'Description of the Promotion', 'VpW5cvYb', 'DEFAULT_F2', 300),
('shuimeicafe.com@gmail.com', 'Promotion of Shui Mei Cafe', 'Description of the Promotion', 'L5cOEIM3', 'DEFAULT_R', 937),
('ulysses.com@gmail.com', 'Promotion of Ulysses', 'Description of the Promotion', '2b4zK5gu', 'DEFAULT_F', 532),
('paradisony.com@gmail.com', 'Promotion of Paradiso Ny', 'Description of the Promotion', '9grHIJXY', 'DEFAULT_R', 940),
('joyluckseafoodrestaurant.com@gmail.com', 'Promotion of Joy Luck Seafood Restaurant', 'Description of the Promotion', 'JEhwXWCZ', 'DEFAULT_F', 222),
('yogurtberry.com@gmail.com', 'Promotion of Yogurtberry', 'Description of the Promotion', 'DLW8Nm65', 'DEFAULT_R2', 756),
('tacohouse.com@gmail.com', 'Promotion of Taco House', 'Description of the Promotion', '9Cc8hSKp', 'DEFAULT_R2', 534),
('valentinospizza.com@gmail.com', 'Promotion of ValentinoS Pizza', 'Description of the Promotion', 'k9XbJfoF', 'DEFAULT_R2', 570),
('saritasbakery.com@gmail.com', 'Promotion of SaritaS Bakery', 'Description of the Promotion', '6avro7DM', 'DEFAULT_F', 388),
('arianascateringhall.com@gmail.com', 'Promotion of Arianas Catering Hall', 'Description of the Promotion', 'Py0zpRH3', 'DEFAULT_F2', 316),
('arianakebabhouse.com@gmail.com', 'Promotion of Ariana Kebab House', 'Description of the Promotion', 'q3JAKB4S', 'DEFAULT_F2', 464),
('vamosaltequila.com@gmail.com', 'Promotion of Vamos Al Tequila', 'Description of the Promotion', 'EXTRMNb0', 'DEFAULT_R2', 968),
('parkcrestfloraldesign.com@gmail.com', 'Promotion of ParkCrest Floral Design', 'Description of the Promotion', 'fOCWsB8T', 'DEFAULT_F2', 550),
('barboulud.com@gmail.com', 'Promotion of Bar Boulud', 'Description of the Promotion', 'xW2ica8r', 'DEFAULT_F', 638),
('theflowerstudio.com@gmail.com', 'Promotion of The Flower Studio', 'Description of the Promotion', '2KrMbDa4', 'DEFAULT_F', 731),
('naturalsurroundings.com@gmail.com', 'Promotion of Natural Surroundings', 'Description of the Promotion', 'diXkrKFN', 'DEFAULT_R2', 479),
('sarkujapanteriyaki&sushiexpress.com@gmail.com', 'Promotion of Sarku Japan Teriyaki & Sushi Express', 'Description of the Promotion', 'NCOVbmoT', 'DEFAULT_R', 232),
('shortstoprestaurant.com@gmail.com', 'Promotion of Short Stop Restaurant', 'Description of the Promotion', '3mGceNJA', 'DEFAULT_R', 790),
('centralsquareflorist.com@gmail.com', 'Promotion of Central Square Florist', 'Description of the Promotion', 'a9gt73T0', 'DEFAULT_F', 339),
('thefolly.com@gmail.com', 'Promotion of The Folly', 'Description of the Promotion', 'IQ0p7TqW', 'DEFAULT_R', 748),
('wasabisushi.com@gmail.com', 'Promotion of Wasabi Sushi', 'Description of the Promotion', '4W2cAo8s', 'DEFAULT_F2', 810),
('cacioevino.com@gmail.com', 'Promotion of Cacio E Vino', 'Description of the Promotion', 'IX2zVndq', 'DEFAULT_R2', 273),
('j.e.bakery.com@gmail.com', 'Promotion of J.E. Bakery', 'Description of the Promotion', 'F5uHyrws', 'DEFAULT_R2', 685),
('babyolive.com@gmail.com', 'Promotion of Baby Olive', 'Description of the Promotion', 'b62mlUT9', 'DEFAULT_R', 764),
('c.u.n.ycafe.com@gmail.com', 'Promotion of C.U.N.Y Cafe', 'Description of the Promotion', 'Cy8Yl3z4', 'DEFAULT_R', 897),
('koa-21llc.com@gmail.com', 'Promotion of Koa-21 Llc', 'Description of the Promotion', 'LJaksdI3', 'DEFAULT_R2', 313),
('zuzuramen.com@gmail.com', 'Promotion of Zuzu Ramen', 'Description of the Promotion', 'yigJESPd', 'DEFAULT_F', 688),
('jamaicafishmarket.com@gmail.com', 'Promotion of Jamaica Fish Market', 'Description of the Promotion', 'z1WpaKsM', 'DEFAULT_F', 222),
('metropizza.com@gmail.com', 'Promotion of Metro Pizza', 'Description of the Promotion', 'pMJ8gZ4E', 'DEFAULT_F', 333),
('zazaborom.com@gmail.com', 'Promotion of Za Zaborom', 'Description of the Promotion', 'ufRyZznS', 'DEFAULT_F', 556),
('c&bpizza.com@gmail.com', 'Promotion of C & B Pizza', 'Description of the Promotion', '6oJe783j', 'DEFAULT_R2', 415),
('olioepiu.com@gmail.com', 'Promotion of Olio E Piu', 'Description of the Promotion', 'wvyQ6Jfn', 'DEFAULT_R2', 359),
('plantparty.com@gmail.com', 'Promotion of Plant Party', 'Description of the Promotion', 'YWmCwpg3', 'DEFAULT_R', 609),
('bloomey’s.com@gmail.com', 'Promotion of Bloomey’s', 'Description of the Promotion', 'M2tixp1I', 'DEFAULT_R', 432),
('jackdemseyspub.com@gmail.com', 'Promotion of Jack DemseyS Pub', 'Description of the Promotion', 'Vi2UkTFE', 'DEFAULT_R', 967),
('diningclubrockefellercenter.com@gmail.com', 'Promotion of Dining Club Rockefeller Center', 'Description of the Promotion', 'XPJ1uE4O', 'DEFAULT_R', 558),
('divineflowers.com@gmail.com', 'Promotion of Divine Flowers', 'Description of the Promotion', 'Mb18HGAq', 'DEFAULT_F', 762),
('kowongrestaurant.com@gmail.com', 'Promotion of Ko Wong Restaurant', 'Description of the Promotion', 'kEVq3STp', 'DEFAULT_R2', 895),
('zaircafe.com@gmail.com', 'Promotion of Zair Cafe', 'Description of the Promotion', 'GzQwpIH5', 'DEFAULT_F2', 993),
('capribakery.com@gmail.com', 'Promotion of Capri Bakery', 'Description of the Promotion', 'YqU2Z7K1', 'DEFAULT_R2', 764),
('baisrochel.com@gmail.com', 'Promotion of Bais Rochel', 'Description of the Promotion', 'jrYiqmT3', 'DEFAULT_F2', 436),
('wilmajean.com@gmail.com', 'Promotion of Wilma Jean', 'Description of the Promotion', '1Xqj60Ke', 'DEFAULT_R', 254),
('gardengirl.com@gmail.com', 'Promotion of Garden Girl', 'Description of the Promotion', '6rzaKyBA', 'DEFAULT_R', 210),
('queensdumplinandeverythingrestaurant.com@gmail.com', 'Promotion of Queens Dumplin And Everything Restaurant', 'Description of the Promotion', 'KNucjWhR', 'DEFAULT_R', 760),
('doublewidebar.com@gmail.com', 'Promotion of Double Wide Bar', 'Description of the Promotion', '5vpIRog1', 'DEFAULT_F2', 584),
('freshflowermarket.com@gmail.com', 'Promotion of Fresh Flower Market', 'Description of the Promotion', 'RntZqsH2', 'DEFAULT_R2', 934),
('barchord.com@gmail.com', 'Promotion of Bar Chord', 'Description of the Promotion', 'nSfBWysF', 'DEFAULT_R', 457),
('doubledutchespresso.com@gmail.com', 'Promotion of Double Dutch Espresso', 'Description of the Promotion', 'WG2ZH03I', 'DEFAULT_F2', 588),
('babalu.com@gmail.com', 'Promotion of Babalu', 'Description of the Promotion', 'n1UPlVqN', 'DEFAULT_F', 336),
('rafi786.com@gmail.com', 'Promotion of Rafi 786', 'Description of the Promotion', 'Q12UoT4Z', 'DEFAULT_F', 773),
('fashionflowers.com@gmail.com', 'Promotion of Fashion Flowers', 'Description of the Promotion', '59Nycnkm', 'DEFAULT_F2', 552),
('italflorist.com@gmail.com', 'Promotion of Ital Florist', 'Description of the Promotion', 'ZU7XR21r', 'DEFAULT_F2', 261),
('strokosgourmetdeli.com@gmail.com', 'Promotion of Strokos Gourmet Deli', 'Description of the Promotion', 's6SqQdVo', 'DEFAULT_F2', 856),
('selectedflower.com@gmail.com', 'Promotion of Selected Flower', 'Description of the Promotion', '3y9j4itb', 'DEFAULT_R', 229),
('olgasrestaurant.com@gmail.com', 'Promotion of OlgaS Restaurant', 'Description of the Promotion', 'ziFVLZ6m', 'DEFAULT_R2', 402),
('casapepe.com@gmail.com', 'Promotion of Casa Pepe', 'Description of the Promotion', 'Hi34SevA', 'DEFAULT_R', 376),
('pacificosfinefoods.com@gmail.com', 'Promotion of Pacificos Fine Foods', 'Description of the Promotion', 'F2LSsKwc', 'DEFAULT_F2', 758),
('theflowercrew.com@gmail.com', 'Promotion of The Flower Crew', 'Description of the Promotion', 'NhC2Mfa6', 'DEFAULT_F2', 346),
('rainbowbouquet.com@gmail.com', 'Promotion of Rainbow Bouquet', 'Description of the Promotion', '8qVCKedr', 'DEFAULT_F', 655),
('eddiesdeli&pizza.com@gmail.com', 'Promotion of Eddies Deli & Pizza', 'Description of the Promotion', 'eRqC7QFi', 'DEFAULT_F2', 402),
('elabuelogozon.com@gmail.com', 'Promotion of El Abuelo Gozon', 'Description of the Promotion', '0kMNla5v', 'DEFAULT_R', 716),
('yofreshnewyork.com@gmail.com', 'Promotion of Yofresh New York', 'Description of the Promotion', 'zri5bKMF', 'DEFAULT_R', 595),
('babaghanouge.com@gmail.com', 'Promotion of Baba Ghanouge', 'Description of the Promotion', 'zfevYqr7', 'DEFAULT_R2', 451),
('vallescafe.com@gmail.com', 'Promotion of ValleS Cafe', 'Description of the Promotion', 'F6SprlsK', 'DEFAULT_F', 795),
('bahbkabctahbka.com@gmail.com', 'Promotion of Bahbka Bctahbka', 'Description of the Promotion', 'ZW4R6rJE', 'DEFAULT_F', 809),
('tacohut.com@gmail.com', 'Promotion of Taco Hut', 'Description of the Promotion', 'jHviSnxE', 'DEFAULT_F', 894),
('c&bluncheonette.com@gmail.com', 'Promotion of C & B Luncheonette', 'Description of the Promotion', 'XMkspLg0', 'DEFAULT_R2', 756),
('aruneethai.com@gmail.com', 'Promotion of Arunee Thai', 'Description of the Promotion', 'PoqOVcYx', 'DEFAULT_R', 263),
('loveandfleurs.com@gmail.com', 'Promotion of Love and Fleurs', 'Description of the Promotion', '3IuwahNV', 'DEFAULT_F2', 462),
('egidiopastry.com@gmail.com', 'Promotion of Egidio Pastry', 'Description of the Promotion', 'w2CxSFgW', 'DEFAULT_R2', 616),
('arepasgrill.com@gmail.com', 'Promotion of Arepas Grill', 'Description of the Promotion', 'gZ3DnGw8', 'DEFAULT_F2', 876),
('nbc.com@gmail.com', 'Promotion of Nbc', 'Description of the Promotion', 'BpjfY9yt', 'DEFAULT_F2', 796),
('thalia.com@gmail.com', 'Promotion of Thalia', 'Description of the Promotion', '5DE4wyAN', 'DEFAULT_F2', 979),
('doublehappykitchen.com@gmail.com', 'Promotion of Double Happy Kitchen', 'Description of the Promotion', 'Ngq6TpMe', 'DEFAULT_R', 522),
('blossomhouse.com@gmail.com', 'Promotion of Blossom House', 'Description of the Promotion', 'wBb3t21h', 'DEFAULT_R', 928),
('dinospizza.com@gmail.com', 'Promotion of Dinos Pizza', 'Description of the Promotion', 'Unk701l2', 'DEFAULT_F2', 691),
('zhiqingactivitycenter.com@gmail.com', 'Promotion of Zhiqing Activity Center', 'Description of the Promotion', 'RjzO2lpb', 'DEFAULT_F2', 547),
('bloomingtrails.com@gmail.com', 'Promotion of Blooming Trails', 'Description of the Promotion', 'yarmjevb', 'DEFAULT_F', 861),
('j.j.bubbles.com@gmail.com', 'Promotion of J.J. Bubbles', 'Description of the Promotion', '0EQ6OqKZ', 'DEFAULT_R2', 685),
('charlessally&charles.com@gmail.com', 'Promotion of Charles Sally & Charles', 'Description of the Promotion', '9LDVUwkm', 'DEFAULT_R', 690),
('frenchbouquet.com@gmail.com', 'Promotion of French Bouquet', 'Description of the Promotion', 'd78JxuyW', 'DEFAULT_R2', 982),
('eisenbergssandwichshop.com@gmail.com', 'Promotion of Eisenbergs Sandwich Shop', 'Description of the Promotion', 'TD10lv2i', 'DEFAULT_F', 659),
('thefoodhut.com@gmail.com', 'Promotion of The Food Hut', 'Description of the Promotion', 'xJc7UFok', 'DEFAULT_R2', 765),
('paradiserestaurantinc..com@gmail.com', 'Promotion of Paradise Restaurant Inc.', 'Description of the Promotion', 'aTBvhzSY', 'DEFAULT_F2', 446),
('strokospizzadeli.com@gmail.com', 'Promotion of Strokos Pizza Deli', 'Description of the Promotion', 'vISXAuWV', 'DEFAULT_F2', 868),
('sashascoffee.com@gmail.com', 'Promotion of SashaS Coffee', 'Description of the Promotion', 'N1mpqvJB', 'DEFAULT_F', 603),
('yogurty23inc.com@gmail.com', 'Promotion of Yogurt Y23 Inc', 'Description of the Promotion', 'Tx91G5wd', 'DEFAULT_R', 618),
('z-onediner&lounge.com@gmail.com', 'Promotion of Z-One Diner & Lounge', 'Description of the Promotion', '0HSWrRTd', 'DEFAULT_R2', 544),
('valenciacoffeeroom.com@gmail.com', 'Promotion of Valencia Coffee Room', 'Description of the Promotion', 'm8Wqt4od', 'DEFAULT_F', 936),
('bahiarestaurant&cafe.com@gmail.com', 'Promotion of Bahia Restaurant & Cafe', 'Description of the Promotion', '3lU8VJby', 'DEFAULT_R2', 406),
('winxinkitchen/tacoking.com@gmail.com', 'Promotion of Win Xin Kitchen/Taco King', 'Description of the Promotion', 'qd3x8sZn', 'DEFAULT_F', 203),
('arianitasrestaurant.com@gmail.com', 'Promotion of Arianitas Restaurant', 'Description of the Promotion', 'vMZl2SzN', 'DEFAULT_R', 777),
('zutto.com@gmail.com', 'Promotion of Zutto', 'Description of the Promotion', 'Kbi3U6Lq', 'DEFAULT_F2', 845),
('caedmonschoolwinsteadcaterers.com@gmail.com', 'Promotion of Caedmon School Winstead Caterers', 'Description of the Promotion', 'VnBWxvcR', 'DEFAULT_R2', 408),
('doublerainbow.com@gmail.com', 'Promotion of Double Rainbow', 'Description of the Promotion', '74FJ51Ve', 'DEFAULT_R2', 493),
('sarkurajapan.com@gmail.com', 'Promotion of Sarkura Japan', 'Description of the Promotion', 'q4H0NVB5', 'DEFAULT_F2', 258),
('rafele.com@gmail.com', 'Promotion of Rafele', 'Description of the Promotion', 'cfqCIADT', 'DEFAULT_R2', 422),
('wimpysrestaurant.com@gmail.com', 'Promotion of WimpyS Restaurant', 'Description of the Promotion', 'oPGNjnRB', 'DEFAULT_F', 217),
('henriettahudson.com@gmail.com', 'Promotion of Henrietta Hudson', 'Description of the Promotion', 'Fua9RwTL', 'DEFAULT_F', 556),
('jamaicabreezerestaurant.com@gmail.com', 'Promotion of Jamaica Breeze Restaurant', 'Description of the Promotion', 'c9OPkS4V', 'DEFAULT_R', 927),
('aretskyspatroon.com@gmail.com', 'Promotion of Aretskys Patroon', 'Description of the Promotion', 'BKIS48u0', 'DEFAULT_R', 609),
('blossom’sfloralartistry.com@gmail.com', 'Promotion of Blossom’s Floral Artistry', 'Description of the Promotion', 'oAwnE2yD', 'DEFAULT_F', 229),
('piepiepizza.com@gmail.com', 'Promotion of Pie Pie Pizza', 'Description of the Promotion', 'EWbAe4nx', 'DEFAULT_R2', 987),
('alibleuflowers&gifts.com@gmail.com', 'Promotion of Ali Bleu Flowers & Gifts', 'Description of the Promotion', 'KzpijhHF', 'DEFAULT_R2', 725),
('kobeyaki.com@gmail.com', 'Promotion of Kobeyaki', 'Description of the Promotion', 'BWUy0NZS', 'DEFAULT_R', 706),
('baisushi.com@gmail.com', 'Promotion of Bai Sushi', 'Description of the Promotion', 'GpsxUwdf', 'DEFAULT_F2', 483),
('theforkbar&grill.com@gmail.com', 'Promotion of The Fork Bar & Grill', 'Description of the Promotion', 'kZxsuM0G', 'DEFAULT_R', 952),
('bloom&bud.com@gmail.com', 'Promotion of Bloom & Bud', 'Description of the Promotion', 'HUz1oOhj', 'DEFAULT_R2', 642),
('xpressions.com@gmail.com', 'Promotion of Xpressions', 'Description of the Promotion', 'qbSi5LuP', 'DEFAULT_F', 206),
('babacool.com@gmail.com', 'Promotion of Baba Cool', 'Description of the Promotion', 'dleMXonW', 'DEFAULT_F', 993),
('sprime.com@gmail.com', 'Promotion of S Prime', 'Description of the Promotion', 'DOYaS5gw', 'DEFAULT_F', 835),
('rosesonly.com@gmail.com', 'Promotion of Roses Only', 'Description of the Promotion', 'Qj46BDbJ', 'DEFAULT_R2', 594),
('byblos.com@gmail.com', 'Promotion of Byblos', 'Description of the Promotion', 'kBQWOLqE', 'DEFAULT_F', 826),
('teleflora.com@gmail.com', 'Promotion of TeleFlora', 'Description of the Promotion', 'h2xGZYqX', 'DEFAULT_R', 785),
('pastai.com@gmail.com', 'Promotion of Pastai', 'Description of the Promotion', 'DAc2Pe6m', 'DEFAULT_R2', 252),
('gardenfresh.com@gmail.com', 'Promotion of Garden Fresh', 'Description of the Promotion', 'DW0B5ey4', 'DEFAULT_R2', 491),
('showpalace.com@gmail.com', 'Promotion of Show Palace', 'Description of the Promotion', '3VAQChWi', 'DEFAULT_F', 323),
('cactus.com@gmail.com', 'Promotion of Cactus', 'Description of the Promotion', '4BNKke2a', 'DEFAULT_F2', 780),
('charlespizzeria.com@gmail.com', 'Promotion of Charles Pizzeria', 'Description of the Promotion', 'P6oSXeaz', 'DEFAULT_F', 335),
('cjsbar&lounge.com@gmail.com', 'Promotion of C Js Bar & Lounge', 'Description of the Promotion', '8KZkbgWX', 'DEFAULT_F2', 744),
('thamma.com@gmail.com', 'Promotion of Thamma', 'Description of the Promotion', '9KV1kEUa', 'DEFAULT_F', 375),
('bairesbakery.com@gmail.com', 'Promotion of Baires Bakery', 'Description of the Promotion', '6YBlG1aC', 'DEFAULT_F2', 271),
('smac.com@gmail.com', 'Promotion of SMac', 'Description of the Promotion', 'ZeirpdkP', 'DEFAULT_F2', 931),
('rightchoice.com@gmail.com', 'Promotion of Right Choice', 'Description of the Promotion', 'NKtwOuTC', 'DEFAULT_R2', 496),
('henrysend.com@gmail.com', 'Promotion of Henrys End', 'Description of the Promotion', 'zrO5QJVS', 'DEFAULT_R', 425),
('pacos.com@gmail.com', 'Promotion of PacoS', 'Description of the Promotion', 'MCUWgu1L', 'DEFAULT_F2', 615),
('kodarestaurant&lounge.com@gmail.com', 'Promotion of Koda Restaurant & Lounge', 'Description of the Promotion', '9OuIonHM', 'DEFAULT_R2', 902),
('pillow.com@gmail.com', 'Promotion of Pillow', 'Description of the Promotion', 'OwDaQjZ0', 'DEFAULT_R', 449),
('doublehappyrestaurant.com@gmail.com', 'Promotion of Double Happy Restaurant', 'Description of the Promotion', 'VdhoeTwN', 'DEFAULT_F', 800),
('krazydaizies.com@gmail.com', 'Promotion of Krazy Daizies', 'Description of the Promotion', 'xiz09ZQR', 'DEFAULT_F2', 246),
('greenitplantsco..com@gmail.com', 'Promotion of Greenit Plants Co.', 'Description of the Promotion', 'xiLazc9l', 'DEFAULT_R', 430),
('metrostarcoffeeshop.com@gmail.com', 'Promotion of Metro Star Coffee Shop', 'Description of the Promotion', 'Jko0buEs', 'DEFAULT_R2', 737),
('yankeeclipper.com@gmail.com', 'Promotion of Yankee Clipper', 'Description of the Promotion', 'itpfzHmQ', 'DEFAULT_R', 778),
('ziemekscafellc.com@gmail.com', 'Promotion of ZiemekS Cafe Llc', 'Description of the Promotion', '3rGnlFEe', 'DEFAULT_R2', 973),
('kosushi.com@gmail.com', 'Promotion of Ko Sushi', 'Description of the Promotion', 'yw0giVZ5', 'DEFAULT_F2', 502),
('packardcafe.com@gmail.com', 'Promotion of Packard  Cafe', 'Description of the Promotion', 'iLwdrBI6', 'DEFAULT_R', 570),
('meditteraneangrill.com@gmail.com', 'Promotion of Meditteranean Grill', 'Description of the Promotion', 'TfjBq5MH', 'DEFAULT_R2', 668),
('villaerasamo.com@gmail.com', 'Promotion of Villa Erasamo', 'Description of the Promotion', 'BtD9aFE0', 'DEFAULT_F2', 407),
('j.d.ssaloonbar.com@gmail.com', 'Promotion of J.D.S Saloon Bar', 'Description of the Promotion', 'KI8d7O0Y', 'DEFAULT_R2', 204),
('bake&thingsrestaurant.com@gmail.com', 'Promotion of Bake & Things Restaurant', 'Description of the Promotion', 'SfCVJ20R', 'DEFAULT_F2', 497),
('urbanstems.com@gmail.com', 'Promotion of Urban Stems', 'Description of the Promotion', '4Y0JXW3P', 'DEFAULT_F', 861),
('kaffkafe.com@gmail.com', 'Promotion of Kaff Kafe', 'Description of the Promotion', 'R5UfAYpm', 'DEFAULT_R2', 789),
('winchesterspub.com@gmail.com', 'Promotion of Winchesters Pub', 'Description of the Promotion', 'CDEnFaxI', 'DEFAULT_R', 731),
('pastelescapy.com@gmail.com', 'Promotion of Pasteles Capy', 'Description of the Promotion', 'joncv4Fq', 'DEFAULT_F2', 593),
('bakeandthingsrestaurant.com@gmail.com', 'Promotion of Bake And Things Restaurant', 'Description of the Promotion', 'tZhyeVCl', 'DEFAULT_R2', 447),
('piepieqcafe.com@gmail.com', 'Promotion of Pie Pie Q Cafe', 'Description of the Promotion', 'z0ElCqNM', 'DEFAULT_R2', 655),
('babygrand.com@gmail.com', 'Promotion of Baby Grand', 'Description of the Promotion', 'KJ7XA0f5', 'DEFAULT_R2', 460),
('eilatrestaurant.com@gmail.com', 'Promotion of Eilat Restaurant', 'Description of the Promotion', '4VMhg3sn', 'DEFAULT_F', 653),
('pie.com@gmail.com', 'Promotion of Pie', 'Description of the Promotion', '9GIzEiqR', 'DEFAULT_R', 874),
('xtreme.com@gmail.com', 'Promotion of Xtreme', 'Description of the Promotion', 'TCUmuAg9', 'DEFAULT_F', 980),
('henrys.com@gmail.com', 'Promotion of Henrys', 'Description of the Promotion', 'pntLZso0', 'DEFAULT_F2', 299),
('babaghanoush.com@gmail.com', 'Promotion of Babaghanoush', 'Description of the Promotion', 'FbMKrVc4', 'DEFAULT_F', 424),
('metronutrition.com@gmail.com', 'Promotion of Metro Nutrition', 'Description of the Promotion', '0GlfEeJp', 'DEFAULT_R', 565),
('bellaflorist.com@gmail.com', 'Promotion of Bella Florist', 'Description of the Promotion', '1RqUCtkK', 'DEFAULT_F2', 723),
('jamaicabreezenyc.com@gmail.com', 'Promotion of Jamaica Breeze Nyc', 'Description of the Promotion', 'VlaKdMi1', 'DEFAULT_R2', 725),
('sdynasty.com@gmail.com', 'Promotion of S Dynasty', 'Description of the Promotion', 'pAPzjK5f', 'DEFAULT_R2', 734),
('ironchefhouse.com@gmail.com', 'Promotion of Iron Chef House', 'Description of the Promotion', 'wE8cWx27', 'DEFAULT_R2', 839),
('yogorino.com@gmail.com', 'Promotion of Yogorino', 'Description of the Promotion', 'F2OeUaCy', 'DEFAULT_F2', 259),
('petalpost.com@gmail.com', 'Promotion of Petal Post', 'Description of the Promotion', 'RItys4Kk', 'DEFAULT_F2', 311),
('aria.com@gmail.com', 'Promotion of Aria', 'Description of the Promotion', 'L7gsrJ1u', 'DEFAULT_R2', 742),
('judy’spetal&blooms.com@gmail.com', 'Promotion of Judy’s Petal & Blooms', 'Description of the Promotion', 'b0jIzK2S', 'DEFAULT_R', 459),
('nayelinrestaurant.com@gmail.com', 'Promotion of Nayelin Restaurant', 'Description of the Promotion', 'cC9TzPOS', 'DEFAULT_F', 790),
('cachapasymas.com@gmail.com', 'Promotion of Cachapas Y Mas', 'Description of the Promotion', 'I9BWmZtb', 'DEFAULT_R', 542),
('rainbowflorists.com@gmail.com', 'Promotion of Rainbow Florists', 'Description of the Promotion', 'VvwjF9lt', 'DEFAULT_R2', 712),
('canadaflowers.com@gmail.com', 'Promotion of Canada Flowers', 'Description of the Promotion', 'a9KmoICw', 'DEFAULT_R', 494),
('flowerhut.com@gmail.com', 'Promotion of Flower Hut', 'Description of the Promotion', 'rmwH2ibt', 'DEFAULT_R2', 657),
('prodigyflower.com@gmail.com', 'Promotion of Prodigy Flower', 'Description of the Promotion', 'D0X7owCT', 'DEFAULT_F', 500),
('babboristoranteeenoteca.com@gmail.com', 'Promotion of Babbo Ristorante E Enoteca', 'Description of the Promotion', 'gvmUQzNn', 'DEFAULT_R', 437),
('tacocity.com@gmail.com', 'Promotion of Taco City', 'Description of the Promotion', 'CgJ2QZl0', 'DEFAULT_F2', 860),
('pieces.com@gmail.com', 'Promotion of Pieces', 'Description of the Promotion', 'BDaAHgem', 'DEFAULT_F2', 593),
('ultimatebakery.com@gmail.com', 'Promotion of Ultimate Bakery', 'Description of the Promotion', 'JZ0nx2UC', 'DEFAULT_F', 984),
('barbruno.com@gmail.com', 'Promotion of Bar Bruno', 'Description of the Promotion', 'SbTZ4NBO', 'DEFAULT_R2', 201),
('nuccisrestaurant.com@gmail.com', 'Promotion of NucciS Restaurant', 'Description of the Promotion', 'VY574Ebo', 'DEFAULT_R', 634),
('heraldsquaremarket.com@gmail.com', 'Promotion of Herald Square Market', 'Description of the Promotion', 'OBzxlinY', 'DEFAULT_F', 398),
('radissonjfk-cafeoneforty.com@gmail.com', 'Promotion of Radisson Jfk- Cafe One Forty', 'Description of the Promotion', '6PlpcLNZ', 'DEFAULT_F2', 505),
('breathtakingblooms.com@gmail.com', 'Promotion of Breathtaking Blooms', 'Description of the Promotion', 'G2uHLTYv', 'DEFAULT_F2', 598),
('winhingfreshtortillas&taco.com@gmail.com', 'Promotion of Win Hing Fresh Tortillas & Taco', 'Description of the Promotion', 'iVS6ph4e', 'DEFAULT_F', 325),
('winhou.com@gmail.com', 'Promotion of Win Hou', 'Description of the Promotion', 'FgwC2bXr', 'DEFAULT_F2', 584),
('yura&companyonmadison.com@gmail.com', 'Promotion of Yura & Company On Madison', 'Description of the Promotion', 'FZAbQslM', 'DEFAULT_R2', 864),
('jacmaochinesecuisine.com@gmail.com', 'Promotion of Jac Mao Chinese Cuisine', 'Description of the Promotion', 'Pad0Xjsz', 'DEFAULT_R2', 250),
('zumstammtisch.com@gmail.com', 'Promotion of Zum Stammtisch', 'Description of the Promotion', 'vNiFKcAD', 'DEFAULT_F', 867),
('kingflorist.com@gmail.com', 'Promotion of King Florist', 'Description of the Promotion', '59A32mvq', 'DEFAULT_R2', 378),
('paradou.com@gmail.com', 'Promotion of Paradou', 'Description of the Promotion', '2meFtTGd', 'DEFAULT_R2', 892),
('charlesalehouse.com@gmail.com', 'Promotion of Charles Ale House', 'Description of the Promotion', '83LrPKYf', 'DEFAULT_R2', 954),
('yogurtcity.com@gmail.com', 'Promotion of Yogurt City', 'Description of the Promotion', 'fJizZkK5', 'DEFAULT_F', 566),
('rosesretailer.com@gmail.com', 'Promotion of Roses Retailer', 'Description of the Promotion', 'ARHd5glk', 'DEFAULT_F', 457),
('queenslibraryemployeecafeteria.com@gmail.com', 'Promotion of Queens Library Employee Cafeteria', 'Description of the Promotion', 'CmeQaLg2', 'DEFAULT_R', 681),
('wasan.com@gmail.com', 'Promotion of Wasan', 'Description of the Promotion', 'CqK0PyZ1', 'DEFAULT_F', 764),
('kahve.com@gmail.com', 'Promotion of Kahve', 'Description of the Promotion', '9H1aVnQy', 'DEFAULT_F2', 558),
('yogurtcouture.com@gmail.com', 'Promotion of Yogurt Couture', 'Description of the Promotion', 'Qp2u6ixG', 'DEFAULT_R2', 742),
('butterflyphilosophy.com@gmail.com', 'Promotion of Butterfly Philosophy', 'Description of the Promotion', 'Iz3gXnTe', 'DEFAULT_F2', 771),
('margotblairfloral.com@gmail.com', 'Promotion of Margot Blair Floral', 'Description of the Promotion', 'cIed7amM', 'DEFAULT_R', 234),
('sagdiana.com@gmail.com', 'Promotion of Sagdiana', 'Description of the Promotion', '8H7UpNZr', 'DEFAULT_F', 304),
('joygardenrestaurant.com@gmail.com', 'Promotion of Joy Garden Restaurant', 'Description of the Promotion', 'fx9miCjL', 'DEFAULT_R', 824),
('s&spizzeriacorp.com@gmail.com', 'Promotion of S&S Pizzeria Corp', 'Description of the Promotion', 'YhlxQXKm', 'DEFAULT_F', 973),
('verbenafloraldesign.com@gmail.com', 'Promotion of Verbena Floral Design', 'Description of the Promotion', '5BdvpMEu', 'DEFAULT_R2', 539),
('artopoliscafe.com@gmail.com', 'Promotion of Artopolis Cafe', 'Description of the Promotion', 'cYoLlpQs', 'DEFAULT_F2', 226),
('cappuccinocafe.com@gmail.com', 'Promotion of Cappuccino Cafe', 'Description of the Promotion', 'ZpTYXIWK', 'DEFAULT_R', 910),
('joyindianrestaurant.com@gmail.com', 'Promotion of Joy Indian Restaurant', 'Description of the Promotion', '6dhskbQD', 'DEFAULT_F', 388),
('zhotel.com@gmail.com', 'Promotion of Z Hotel', 'Description of the Promotion', '2pKAwnys', 'DEFAULT_F2', 673),
('sunnyflorists.com@gmail.com', 'Promotion of Sunny Florists', 'Description of the Promotion', 'ojVRYCeA', 'DEFAULT_F', 630),
('koelnerbierhalle.com@gmail.com', 'Promotion of Koelner Bier Halle', 'Description of the Promotion', 'xfaZXKdn', 'DEFAULT_F', 622),
('mapleleafflower.com@gmail.com', 'Promotion of MapleLeaf Flower', 'Description of the Promotion', 'eXMV1Hl0', 'DEFAULT_R', 667),
('babybosburritos.com@gmail.com', 'Promotion of Baby BoS Burritos', 'Description of the Promotion', 'XVgv9zGM', 'DEFAULT_R2', 580),
('rose&co.com@gmail.com', 'Promotion of Rose & Co', 'Description of the Promotion', 'sLx6u42V', 'DEFAULT_F2', 845),
('kendallflowershop.com@gmail.com', 'Promotion of Kendall Flower Shop', 'Description of the Promotion', 'qZaFCygs', 'DEFAULT_F2', 996),
('nb.nationalbakery.com@gmail.com', 'Promotion of Nb. National Bakery', 'Description of the Promotion', 'QT86Sk3l', 'DEFAULT_F2', 981),
('sscalabropizzeria.com@gmail.com', 'Promotion of S S Calabro Pizzeria', 'Description of the Promotion', 'HWv5qFsk', 'DEFAULT_R2', 420),
('cabana.com@gmail.com', 'Promotion of Cabana', 'Description of the Promotion', 'IVdygoCe', 'DEFAULT_R2', 715),
('doubledragonrestaurant.com@gmail.com', 'Promotion of Double Dragon Restaurant', 'Description of the Promotion', 'BqyFtEpg', 'DEFAULT_R', 256),
('intin.y.c..com@gmail.com', 'Promotion of Inti N.Y.C.', 'Description of the Promotion', 'bgWq1BI0', 'DEFAULT_F', 657),
('oishiijapansestex-mex.com@gmail.com', 'Promotion of Oishii Japanses Tex-Mex', 'Description of the Promotion', 'BxQ45fyO', 'DEFAULT_F', 766),
('lapetitebouquet.com@gmail.com', 'Promotion of La Petite Bouquet', 'Description of the Promotion', 'Vjyqr93O', 'DEFAULT_F2', 841),
('valianopizza.com@gmail.com', 'Promotion of Valiano Pizza', 'Description of the Promotion', 'k4Yfx9A8', 'DEFAULT_F2', 792),
('flowersforeveryone.com@gmail.com', 'Promotion of Flowers For Everyone', 'Description of the Promotion', 'oC1UvkSq', 'DEFAULT_F', 411),
('mediterraneo.com@gmail.com', 'Promotion of Mediterraneo', 'Description of the Promotion', 'Fx8Ay3Ys', 'DEFAULT_F2', 206),
('casanova.com@gmail.com', 'Promotion of Casa Nova', 'Description of the Promotion', 'fq6QwI80', 'DEFAULT_F', 454),
('theflyinglobster.com@gmail.com', 'Promotion of The Flying Lobster', 'Description of the Promotion', 'Pub56iAq', 'DEFAULT_R2', 893),
('studebakercafe.com@gmail.com', 'Promotion of Studebaker Cafe', 'Description of the Promotion', 'ZlgW5UPn', 'DEFAULT_F2', 595),
('onioncreekflowers.com@gmail.com', 'Promotion of Onion Creek Flowers', 'Description of the Promotion', 'NtlOfMXP', 'DEFAULT_R2', 207),
('sagaponack.com@gmail.com', 'Promotion of Sagaponack', 'Description of the Promotion', 'iOIM9mNS', 'DEFAULT_R2', 485),
('zafisluncheonette.com@gmail.com', 'Promotion of ZafiS Luncheonette', 'Description of the Promotion', 'n60jic7s', 'DEFAULT_F2', 540),
('flowersforyou.com@gmail.com', 'Promotion of Flowers For You', 'Description of the Promotion', 'kSm3oNs2', 'DEFAULT_R', 386),
('villaelbacatering.com@gmail.com', 'Promotion of Villa Elba Catering', 'Description of the Promotion', 'QtDn6R3L', 'DEFAULT_R2', 228),
('zagarawinebar.com@gmail.com', 'Promotion of Zagara Wine Bar', 'Description of the Promotion', '4wVJoy2T', 'DEFAULT_R2', 766),
('barcorvo.com@gmail.com', 'Promotion of Bar Corvo', 'Description of the Promotion', 'YsqEiSU0', 'DEFAULT_F2', 640),
('rainbowroom.com@gmail.com', 'Promotion of Rainbow Room', 'Description of the Promotion', 'FiWjhBmf', 'DEFAULT_R2', 263),
('zablozkis.com@gmail.com', 'Promotion of Zablozkis', 'Description of the Promotion', 'o8FlqpQP', 'DEFAULT_F', 700),
('eddiesheroplace.com@gmail.com', 'Promotion of Eddies Hero Place', 'Description of the Promotion', '3AXYWeB6', 'DEFAULT_R2', 831),
('safra.com@gmail.com', 'Promotion of Safra', 'Description of the Promotion', 'eolFuzr0', 'DEFAULT_F2', 861),
('yungsunseafoodrestaurant.com@gmail.com', 'Promotion of Yung Sun Seafood Restaurant', 'Description of the Promotion', 'Hl6hyJVM', 'DEFAULT_F2', 475),
('bloomcouture.com@gmail.com', 'Promotion of Bloom Couture', 'Description of the Promotion', 'LC2W9vgm', 'DEFAULT_F2', 521),
('barcentrale.com@gmail.com', 'Promotion of Bar Centrale', 'Description of the Promotion', '4f7lphx8', 'DEFAULT_F', 929),
('villamarrestaurant.com@gmail.com', 'Promotion of Villa Mar Restaurant', 'Description of the Promotion', 'N968z7l5', 'DEFAULT_R', 654),
('olgaspizza.com@gmail.com', 'Promotion of OlgaS Pizza', 'Description of the Promotion', 'T51UCyar', 'DEFAULT_F', 932),
('queensconcessionstand.com@gmail.com', 'Promotion of Queens Concession Stand', 'Description of the Promotion', '5EGz32LA', 'DEFAULT_F', 517),
('bloomex.com@gmail.com', 'Promotion of Bloomex', 'Description of the Promotion', 'VgBh6v5i', 'DEFAULT_R2', 470),
('milonbangladesh&indianrestaurant.com@gmail.com', 'Promotion of Milon Bangladesh & Indian Restaurant', 'Description of the Promotion', 'C1uR4Lrc', 'DEFAULT_F2', 248),
('pacificanarest.com@gmail.com', 'Promotion of Pacificana Rest', 'Description of the Promotion', 'P1pna9Yu', 'DEFAULT_F2', 306),
('mccoyspub.com@gmail.com', 'Promotion of MccoyS Pub', 'Description of the Promotion', 'qxOjQLhu', 'DEFAULT_R', 794),
('internationalwingsfactory.com@gmail.com', 'Promotion of International Wings Factory', 'Description of the Promotion', 'y5hlD9t6', 'DEFAULT_F', 708),
('tacogrill.com@gmail.com', 'Promotion of Taco Grill', 'Description of the Promotion', '2NveWSwT', 'DEFAULT_F2', 506),
('pastafinapizza.com@gmail.com', 'Promotion of Pastafina Pizza', 'Description of the Promotion', '3pwfgOZB', 'DEFAULT_F', 983),
('dillingerspub&grill.com@gmail.com', 'Promotion of Dillingers Pub & Grill', 'Description of the Promotion', 'bf3uc0GO', 'DEFAULT_R2', 445),
('arharnthaicuisine.com@gmail.com', 'Promotion of Arharn Thai Cuisine', 'Description of the Promotion', 'd7p9kFHC', 'DEFAULT_R2', 888),
('nazbakery&rotishop.com@gmail.com', 'Promotion of Naz Bakery & Roti Shop', 'Description of the Promotion', 'tzVUNwm1', 'DEFAULT_F2', 267),
('capizzi.com@gmail.com', 'Promotion of Capizzi', 'Description of the Promotion', 'SY7xvopR', 'DEFAULT_F', 486),
('zumbarestaurant.com@gmail.com', 'Promotion of Zumba Restaurant', 'Description of the Promotion', 'JmbfxDnt', 'DEFAULT_F', 938),
('koftepiyazrestaurant.com@gmail.com', 'Promotion of Kofte Piyaz Restaurant', 'Description of the Promotion', 'SkWRs9b0', 'DEFAULT_R2', 680),
('villagardenfamouspizza.com@gmail.com', 'Promotion of Villa Garden Famous Pizza', 'Description of the Promotion', 'WHmC7DSs', 'DEFAULT_F2', 466),
('petesgrill.com@gmail.com', 'Promotion of PeteS Grill', 'Description of the Promotion', 'psbOR89h', 'DEFAULT_F', 847),
('zahlayasbistro.com@gmail.com', 'Promotion of ZahlayaS Bistro', 'Description of the Promotion', 'gM8Naymq', 'DEFAULT_R2', 772),
('laura’sgarden.com@gmail.com', 'Promotion of Laura’s Garden', 'Description of the Promotion', 'XwIE7sSL', 'DEFAULT_F2', 485),
('artsandcraftsbeerparlor.com@gmail.com', 'Promotion of Arts And Crafts Beer Parlor', 'Description of the Promotion', 'LPsTht3J', 'DEFAULT_F', 376),
('coleen’sflowershop.com@gmail.com', 'Promotion of Coleen’s Flower Shop', 'Description of the Promotion', 'GiZnOgKX', 'DEFAULT_F2', 765),
('joykitchenchineserestaurant.com@gmail.com', 'Promotion of Joy Kitchen Chinese Restaurant', 'Description of the Promotion', 'GVT7YkBW', 'DEFAULT_R2', 481),
('artusopastryshop.com@gmail.com', 'Promotion of Artuso Pastry Shop', 'Description of the Promotion', 'XGlzLYMK', 'DEFAULT_F', 306),
('baked.com@gmail.com', 'Promotion of Baked', 'Description of the Promotion', 'KsF8Ttrx', 'DEFAULT_R2', 691),
('sarilingatin.com@gmail.com', 'Promotion of Sariling Atin', 'Description of the Promotion', 'UcOSNqer', 'DEFAULT_F2', 871),
('abetterflorist.com@gmail.com', 'Promotion of A Better Florist', 'Description of the Promotion', 'uXEvBAbT', 'DEFAULT_F2', 871),
('willisnorthamerica.com@gmail.com', 'Promotion of Willis North America', 'Description of the Promotion', 'sTkVECrd', 'DEFAULT_R', 314),
('joya.com@gmail.com', 'Promotion of Joya', 'Description of the Promotion', 'dGoF42w8', 'DEFAULT_F2', 706),
('backbayflorist.com@gmail.com', 'Promotion of Back Bay Florist', 'Description of the Promotion', 'EN67sdAm', 'DEFAULT_R', 548),
('fancyflowersandgifts.com@gmail.com', 'Promotion of Fancy Flowers And Gifts', 'Description of the Promotion', 'PquYMHiD', 'DEFAULT_F', 818),
('flowersforher.com@gmail.com', 'Promotion of Flowers For Her', 'Description of the Promotion', 'yikfVJGg', 'DEFAULT_F', 380),
('mcdonald.com@gmail.com', 'Promotion of Mcdonald', 'Description of the Promotion', 'hnZVH7IS', 'DEFAULT_R2', 379),
('o.m.flowershop.com@gmail.com', 'Promotion of O.M. Flower Shop', 'Description of the Promotion', '9TctXWJ2', 'DEFAULT_R2', 829),
('thainy.com@gmail.com', 'Promotion of Thainy', 'Description of the Promotion', '4Ulgpf9S', 'DEFAULT_R2', 203),
('pacha.com@gmail.com', 'Promotion of Pacha', 'Description of the Promotion', 'VbWAgKw1', 'DEFAULT_F2', 516),
('zuccabucafrozenyogurt.com@gmail.com', 'Promotion of Zucca Buca Frozen Yogurt', 'Description of the Promotion', 'KYEyewQf', 'DEFAULT_R', 977),
('jamrock.com@gmail.com', 'Promotion of Jam Rock', 'Description of the Promotion', 'vpZICBen', 'DEFAULT_R2', 857),
('rafaelinarestaurant&barcorp.com@gmail.com', 'Promotion of Rafaelina Restaurant & Bar Corp', 'Description of the Promotion', '2SX4mZVi', 'DEFAULT_F2', 323),
('pinchetaquiera.com@gmail.com', 'Promotion of Pinche Taquiera', 'Description of the Promotion', 'tCa2HiMh', 'DEFAULT_F', 722),
('wolff’sfloraldesigns.com@gmail.com', 'Promotion of Wolff’s Floral Designs', 'Description of the Promotion', '0fFM4zSy', 'DEFAULT_R', 313),
('sasabuneexpressnewyork.com@gmail.com', 'Promotion of Sasabune Express New York', 'Description of the Promotion', 'OfuBNepQ', 'DEFAULT_F2', 254),
('cieloatthemayfair.com@gmail.com', 'Promotion of Cielo At The Mayfair', 'Description of the Promotion', 'xZrTNm7S', 'DEFAULT_R2', 973),
('c&ccatering.com@gmail.com', 'Promotion of C & C Catering', 'Description of the Promotion', 'hJFYOH36', 'DEFAULT_R', 810),
('pekingkitchenchinesecuisine.com@gmail.com', 'Promotion of Peking Kitchen Chinese Cuisine', 'Description of the Promotion', 'g4FjZqzI', 'DEFAULT_R2', 350),
('olympiaflowerstore.com@gmail.com', 'Promotion of Olympia Flower Store', 'Description of the Promotion', 'JdoqE1Zl', 'DEFAULT_R', 933),
('tacoexpress.com@gmail.com', 'Promotion of Taco Express', 'Description of the Promotion', '6CkjifdJ', 'DEFAULT_F2', 366),
('flowerbros.com@gmail.com', 'Promotion of Flower Bros', 'Description of the Promotion', 'UP8om7n5', 'DEFAULT_F', 719),
('raffaello.com@gmail.com', 'Promotion of Raffaello', 'Description of the Promotion', 'PiAX1sfI', 'DEFAULT_F', 714),
('joygarden.com@gmail.com', 'Promotion of Joy Garden', 'Description of the Promotion', '071n3tbE', 'DEFAULT_R2', 267),
('townhallflowers.com@gmail.com', 'Promotion of Town Hall Flowers', 'Description of the Promotion', 'XQ0Tlpxy', 'DEFAULT_F2', 575),
('xtracheesepizzeria.com@gmail.com', 'Promotion of Xtra Cheese Pizzeria', 'Description of the Promotion', 'ZKM8p2Iw', 'DEFAULT_F2', 663),
('villaitaliankitchen.com@gmail.com', 'Promotion of Villa Italian Kitchen', 'Description of the Promotion', 'X4RZamks', 'DEFAULT_R', 514),
('egyptiancoffeeshop.com@gmail.com', 'Promotion of Egyptian Coffee Shop', 'Description of the Promotion', 'a1Jmso0u', 'DEFAULT_R', 448),
('barcatalonia.com@gmail.com', 'Promotion of Bar Catalonia', 'Description of the Promotion', 'wUOEBFW5', 'DEFAULT_F', 228),
('washingtonbagelcafe.com@gmail.com', 'Promotion of Washington Bagel Cafe', 'Description of the Promotion', 'qrvSgUzw', 'DEFAULT_R2', 518),
('showmanscafe.com@gmail.com', 'Promotion of ShowmanS Cafe', 'Description of the Promotion', 'jinwMNB7', 'DEFAULT_R2', 882),
('pacifickitchen.com@gmail.com', 'Promotion of Pacific Kitchen', 'Description of the Promotion', 'jvCY4fqy', 'DEFAULT_F', 960),
('umamiburger.com@gmail.com', 'Promotion of Umami Burger', 'Description of the Promotion', 'Mfucr6nK', 'DEFAULT_R', 928),
('pasteskikosnewyork.com@gmail.com', 'Promotion of Pastes KikoS New York', 'Description of the Promotion', 'QI3d85Vl', 'DEFAULT_F', 865),
('shqiperiacafe.com@gmail.com', 'Promotion of Shqiperia Cafe', 'Description of the Promotion', 'Vb3iap5e', 'DEFAULT_F', 528),
('studio151.com@gmail.com', 'Promotion of Studio 151', 'Description of the Promotion', 'MUB3xolk', 'DEFAULT_R', 854),
('ohanajapanesehibachiseafood&steak.com@gmail.com', 'Promotion of Ohana Japanese Hibachi Seafood & Steak', 'Description of the Promotion', 'jtv0lbI3', 'DEFAULT_R', 279),
('dimsumgogo.com@gmail.com', 'Promotion of Dim Sum Go Go', 'Description of the Promotion', 'PkOLtKzh', 'DEFAULT_F2', 670),
('littlefoxflowers.com@gmail.com', 'Promotion of Little Fox Flowers', 'Description of the Promotion', 'vTi0tBJ3', 'DEFAULT_F', 338),
('thaitonys.com@gmail.com', 'Promotion of Thai TonyS', 'Description of the Promotion', 'V9vCY8L6', 'DEFAULT_R', 930),
('dinodots.com@gmail.com', 'Promotion of Dino Dots', 'Description of the Promotion', 'FuxpWTlO', 'DEFAULT_R', 570),
('radiostar.com@gmail.com', 'Promotion of Radio Star', 'Description of the Promotion', '5HuP6r9l', 'DEFAULT_R', 724),
('dino.com@gmail.com', 'Promotion of Dino', 'Description of the Promotion', 'jw5foMHc', 'DEFAULT_R', 202),
('c.m.coffeeshop.com@gmail.com', 'Promotion of C.M. Coffee Shop', 'Description of the Promotion', 'CspmVYMA', 'DEFAULT_F', 468),
('buds2blooms.com@gmail.com', 'Promotion of Buds 2 Blooms', 'Description of the Promotion', 'KhE2DFxG', 'DEFAULT_F2', 680),
('cadwalader,wickersham&taft.com@gmail.com', 'Promotion of Cadwalader, Wickersham & Taft', 'Description of the Promotion', '3LBHXu27', 'DEFAULT_R', 422),
('morningglory.com@gmail.com', 'Promotion of Morning Glory', 'Description of the Promotion', 'TizAv19B', 'DEFAULT_F', 538),
('nellie’swildflowers.com@gmail.com', 'Promotion of Nellie’s Wild Flowers', 'Description of the Promotion', '6sNjPtQJ', 'DEFAULT_R', 733),
('babaspierogies.com@gmail.com', 'Promotion of Babas Pierogies', 'Description of the Promotion', 'k7olhNtE', 'DEFAULT_F', 570),
('dinastiachina.com@gmail.com', 'Promotion of Dinastia China', 'Description of the Promotion', 'Zr8qXu2a', 'DEFAULT_R2', 589),
('mcdermottspub.com@gmail.com', 'Promotion of McdermottS Pub', 'Description of the Promotion', '6xLHtqin', 'DEFAULT_F', 818),
('eim.com@gmail.com', 'Promotion of Eim', 'Description of the Promotion', '5TP41fpL', 'DEFAULT_R', 1000),
('pinchetaqueria.com@gmail.com', 'Promotion of Pinche Taqueria', 'Description of the Promotion', 'YVH68FRA', 'DEFAULT_F', 297),
('zabbelee.com@gmail.com', 'Promotion of Zabb Elee', 'Description of the Promotion', 'u6P3j2KE', 'DEFAULT_R', 867),
('blessedstems.com@gmail.com', 'Promotion of Blessed Stems', 'Description of the Promotion', 'qr4h9Qsl', 'DEFAULT_F', 624),
('zuckersbagelsandsmokedfish.com@gmail.com', 'Promotion of ZuckerS Bagels And Smoked Fish', 'Description of the Promotion', 'WsrGmRVD', 'DEFAULT_R2', 870),
('wilmerhale.com@gmail.com', 'Promotion of Wilmer Hale', 'Description of the Promotion', 'TrVB5hEs', 'DEFAULT_R2', 927),
('pinebar&grill.com@gmail.com', 'Promotion of Pine Bar & Grill', 'Description of the Promotion', 'XdkCR9cn', 'DEFAULT_R2', 637),
('westbankflowermarket.com@gmail.com', 'Promotion of Westbank Flower Market', 'Description of the Promotion', 'nljywS4Y', 'DEFAULT_F', 249),
('wasabipoint.com@gmail.com', 'Promotion of Wasabi Point', 'Description of the Promotion', '1WYj7xbJ', 'DEFAULT_F2', 221),
('pimentocarribeanrestaurant.com@gmail.com', 'Promotion of Pimento Carribean Restaurant', 'Description of the Promotion', 'z3JesThL', 'DEFAULT_R2', 694),
('floramor.com@gmail.com', 'Promotion of Flor Amor', 'Description of the Promotion', 'gCcJGDvz', 'DEFAULT_R', 325),
('oishibaysushirestaurant.com@gmail.com', 'Promotion of Oishi Baysushi Restaurant', 'Description of the Promotion', '9oYsIzSF', 'DEFAULT_R', 625),
('internationalhouse.com@gmail.com', 'Promotion of Internationalhouse', 'Description of the Promotion', 'lWCA87Dt', 'DEFAULT_F', 496),
('ironsushi.com@gmail.com', 'Promotion of Iron Sushi', 'Description of the Promotion', 'xcFuv4wW', 'DEFAULT_F', 871),
('umaijapaneserestaurant.com@gmail.com', 'Promotion of Umai Japanese Restaurant', 'Description of the Promotion', '03RLuB2M', 'DEFAULT_F2', 331),
('pachangapatterson.com@gmail.com', 'Promotion of Pachanga Patterson', 'Description of the Promotion', 'mUN6hFSY', 'DEFAULT_R2', 484),
('kim’sflowershop.com@gmail.com', 'Promotion of Kim’s Flower Shop', 'Description of the Promotion', 'DcxhW2u6', 'DEFAULT_R', 879),
('koffeecakecorner.com@gmail.com', 'Promotion of Koffeecake Corner', 'Description of the Promotion', 'FcifOSHN', 'DEFAULT_F', 985),
('raescafe.com@gmail.com', 'Promotion of RaeS Cafe', 'Description of the Promotion', 'ImeqkViF', 'DEFAULT_R', 467),
('eightturncrepe.com@gmail.com', 'Promotion of Eight Turn Crepe', 'Description of the Promotion', '018udx74', 'DEFAULT_R2', 458),
('jayne’sflowers.com@gmail.com', 'Promotion of Jayne’s Flowers', 'Description of the Promotion', 'zueBsDF4', 'DEFAULT_F', 587),
('shuhanjuauthenticchinesecuisine.com@gmail.com', 'Promotion of Shu Han Ju Authentic Chinese Cuisine', 'Description of the Promotion', 'n84HRqED', 'DEFAULT_F2', 853),
('zuckerbakery.com@gmail.com', 'Promotion of Zucker Bakery', 'Description of the Promotion', 'mUNMxLEB', 'DEFAULT_F2', 760),
('pacificmoon.com@gmail.com', 'Promotion of Pacific Moon', 'Description of the Promotion', '9Y1QmJHn', 'DEFAULT_F', 895),
('henryst.alehouse.com@gmail.com', 'Promotion of Henry St. Ale House', 'Description of the Promotion', 'fbAK8GXM', 'DEFAULT_R2', 787),
('cilantro.com@gmail.com', 'Promotion of Cilantro', 'Description of the Promotion', 'KFyiqPbj', 'DEFAULT_R', 225),
('pekingkitchen.com@gmail.com', 'Promotion of Peking Kitchen', 'Description of the Promotion', 'mTAIKOZt', 'DEFAULT_F2', 835),
('irishrover.com@gmail.com', 'Promotion of Irish Rover', 'Description of the Promotion', '4cFL3yXt', 'DEFAULT_F', 871),
('zibettoespressobar.com@gmail.com', 'Promotion of Zibetto Espresso Bar', 'Description of the Promotion', 'hw1AVTFn', 'DEFAULT_R2', 304),
('benwhiteflorist.com@gmail.com', 'Promotion of Ben White Florist', 'Description of the Promotion', '3Ytc48xn', 'DEFAULT_F', 878),
('artofbloomflorist.com@gmail.com', 'Promotion of Art of Bloom Florist', 'Description of the Promotion', 'q0GinpPm', 'DEFAULT_F2', 903),
('dhel’sflowers.com@gmail.com', 'Promotion of Dhel’s Flowers', 'Description of the Promotion', 'dHK5veiU', 'DEFAULT_F', 845),
('edenwok.com@gmail.com', 'Promotion of Eden Wok', 'Description of the Promotion', 'TNLZuHOB', 'DEFAULT_R', 941),
('pekingkitchenii.com@gmail.com', 'Promotion of Peking Kitchen Ii', 'Description of the Promotion', 'bz4TioX8', 'DEFAULT_F', 267),
('sage.com@gmail.com', 'Promotion of Sage', 'Description of the Promotion', 'GurLzHv2', 'DEFAULT_F2', 491),
('piece-a-cakebakery.com@gmail.com', 'Promotion of Piece-A-Cake Bakery', 'Description of the Promotion', 'qZHYNU4V', 'DEFAULT_R2', 598),
('whitelotusflowers.com@gmail.com', 'Promotion of White Lotus Flowers', 'Description of the Promotion', 'vP5Dce8W', 'DEFAULT_F', 888),
('blackorchidfloraldesign.com@gmail.com', 'Promotion of Black Orchid Floral Design', 'Description of the Promotion', 'mGXh3IYo', 'DEFAULT_F', 228),
('yogurtinlove.com@gmail.com', 'Promotion of Yogurt In Love', 'Description of the Promotion', 'WlV9gF8L', 'DEFAULT_R2', 795),
('jack&nellies.com@gmail.com', 'Promotion of Jack & NellieS', 'Description of the Promotion', 'DTPnYGbq', 'DEFAULT_F2', 599),
('pastelitoselvys.com@gmail.com', 'Promotion of Pastelitos Elvys', 'Description of the Promotion', 'Muq9ezav', 'DEFAULT_R', 616),
('valbonarestaurant.com@gmail.com', 'Promotion of Valbona Restaurant', 'Description of the Promotion', 'I5Wlx97b', 'DEFAULT_F', 741),
('edibleblooms.com@gmail.com', 'Promotion of Edible Blooms', 'Description of the Promotion', 'EO2mRuhi', 'DEFAULT_F2', 552),
('irohajapaneserestaurant.com@gmail.com', 'Promotion of Iroha Japanese Restaurant', 'Description of the Promotion', '27D51fIj', 'DEFAULT_R2', 434),
('zhongwahchineserestaurant.com@gmail.com', 'Promotion of Zhong Wah Chinese Restaurant', 'Description of the Promotion', 'sj7RohmQ', 'DEFAULT_R', 205),
('arianarestaurant.com@gmail.com', 'Promotion of Ariana Restaurant', 'Description of the Promotion', 'RIMqoW9Q', 'DEFAULT_R2', 992),
('rosevalley.com@gmail.com', 'Promotion of Rose Valley', 'Description of the Promotion', 'ogJ0KPB5', 'DEFAULT_F', 340),
('caterinaspizzeria.com@gmail.com', 'Promotion of Caterinas Pizzeria', 'Description of the Promotion', 'NUC5Bjgu', 'DEFAULT_F2', 301),
('sweetheartflorist.com@gmail.com', 'Promotion of Sweetheart Florist', 'Description of the Promotion', 'AJj2IbYq', 'DEFAULT_R2', 933),
('williessteakhouse.com@gmail.com', 'Promotion of WillieS Steak House', 'Description of the Promotion', 'wYPHBzqF', 'DEFAULT_F2', 247),
('yuvafrontierindiangrill.com@gmail.com', 'Promotion of Yuva Frontier Indian Grill', 'Description of the Promotion', 'zO3itUe5', 'DEFAULT_R', 483),
('florista.com@gmail.com', 'Promotion of Florista', 'Description of the Promotion', 'ADfSLgNm', 'DEFAULT_R2', 624),
('petespizza.com@gmail.com', 'Promotion of PeteS Pizza', 'Description of the Promotion', 'gECJQ6aO', 'DEFAULT_R', 245),
('millyscornerrestaurantandbar.com@gmail.com', 'Promotion of MillyS Corner Restaurant And Bar', 'Description of the Promotion', 'iLlU2WKj', 'DEFAULT_F2', 856),
('onda.com@gmail.com', 'Promotion of Onda', 'Description of the Promotion', 'sSVnX4DL', 'DEFAULT_F', 553),
('sami’sflowershop.com@gmail.com', 'Promotion of Sami’s Flower Shop', 'Description of the Promotion', '1utIxFr5', 'DEFAULT_R', 685),
('cienfuegos.com@gmail.com', 'Promotion of Cien Fuegos', 'Description of the Promotion', 'MHqtDUzm', 'DEFAULT_F2', 750),
('winchineserestaurant.com@gmail.com', 'Promotion of Win Chinese Restaurant', 'Description of the Promotion', '8Uzof7XK', 'DEFAULT_F2', 578),
('barcoastal.com@gmail.com', 'Promotion of Bar Coastal', 'Description of the Promotion', '7XbJvmCr', 'DEFAULT_F', 983),
('nayamezze&grill.com@gmail.com', 'Promotion of Naya Mezze & Grill', 'Description of the Promotion', 'xygY5MPF', 'DEFAULT_R', 956),
('petesclamstop.com@gmail.com', 'Promotion of PeteS Clam Stop', 'Description of the Promotion', 'JoyDaVS4', 'DEFAULT_F', 654),
('rosebay.com@gmail.com', 'Promotion of Rose Bay', 'Description of the Promotion', 'BDeuaqgk', 'DEFAULT_F2', 512),
('dingdong.com@gmail.com', 'Promotion of Ding Dong', 'Description of the Promotion', '4hP6U0Yj', 'DEFAULT_R', 623),
('eggwell.com@gmail.com', 'Promotion of Eggwell', 'Description of the Promotion', 'TdUr2Z0M', 'DEFAULT_R', 681),
('piecorps.com@gmail.com', 'Promotion of Pie Corps', 'Description of the Promotion', 'Er12DyWB', 'DEFAULT_R2', 746),
('herbalife.com@gmail.com', 'Promotion of Herbalife', 'Description of the Promotion', 'Do69EQI3', 'DEFAULT_R', 381),
('ukrainianrestaurant.com@gmail.com', 'Promotion of Ukrainian Restaurant', 'Description of the Promotion', 'p51YZNj6', 'DEFAULT_R', 489),
('bailichineserestaurant.com@gmail.com', 'Promotion of Bai Li Chinese Restaurant', 'Description of the Promotion', 'O2DICZzx', 'DEFAULT_F', 311),
('mccannspub.com@gmail.com', 'Promotion of MccannS Pub', 'Description of the Promotion', 'PY1kZt9h', 'DEFAULT_R2', 922),
('propertyflower.com@gmail.com', 'Promotion of Property Flower', 'Description of the Promotion', '8rvdfbUF', 'DEFAULT_R2', 314),
('magpieblossomboutique.com@gmail.com', 'Promotion of Magpie Blossom Boutique', 'Description of the Promotion', 'PwJjpWkm', 'DEFAULT_F2', 717),
('shuberttheater.com@gmail.com', 'Promotion of Shubert Theater', 'Description of the Promotion', '6x8ODmqt', 'DEFAULT_R2', 577),
('barbrace.com@gmail.com', 'Promotion of Bar Brace', 'Description of the Promotion', 'QUEXdJ10', 'DEFAULT_R2', 305),
('shukmediterraneancuisine.com@gmail.com', 'Promotion of Shuk Mediterranean Cuisine', 'Description of the Promotion', 'FnKh3jCq', 'DEFAULT_R', 684),
('wimpysrestaurant.com@gmail.com', 'Promotion of Wimpys Restaurant', 'Description of the Promotion', 'oPab6deA', 'DEFAULT_R', 532),
('winhingchineserestaurant.com@gmail.com', 'Promotion of Win Hing Chinese Restaurant', 'Description of the Promotion', 'oTgN5ADy', 'DEFAULT_F', 736),
('kaffe3,inc..com@gmail.com', 'Promotion of Kaffe 3, Inc.', 'Description of the Promotion', 'JRfzYLSu', 'DEFAULT_F', 747),
('hermesbilliards&cafe.com@gmail.com', 'Promotion of Hermes Billiards & Cafe', 'Description of the Promotion', '6AqmQYvR', 'DEFAULT_R2', 231),
('ultimategrill.com@gmail.com', 'Promotion of Ultimate Grill', 'Description of the Promotion', 'WTBq0hE6', 'DEFAULT_F', 796),
('looseleaf.com@gmail.com', 'Promotion of Loose Leaf', 'Description of the Promotion', '9R5V7Z3D', 'DEFAULT_F', 604),
('millyspizzeria.com@gmail.com', 'Promotion of MillyS Pizzeria', 'Description of the Promotion', 'Wvp7X2nB', 'DEFAULT_F2', 849),
('dinospizza&pasta.com@gmail.com', 'Promotion of Dinos Pizza & Pasta', 'Description of the Promotion', 'czINSJrl', 'DEFAULT_F', 296),
('theflyingpuck.com@gmail.com', 'Promotion of The Flying Puck', 'Description of the Promotion', 'N7hDaH0e', 'DEFAULT_R2', 202),
('thaivillage.com@gmail.com', 'Promotion of Thai Village', 'Description of the Promotion', 'x1jRuwLW', 'DEFAULT_R', 888),
('j.rscabaret.com@gmail.com', 'Promotion of J.Rs Cabaret', 'Description of the Promotion', 'Tpgjahzn', 'DEFAULT_R2', 949),
('yankarisquaresoul2soul.com@gmail.com', 'Promotion of Yankari Square Soul 2 Soul', 'Description of the Promotion', '7Lh6GT1l', 'DEFAULT_F2', 498),
('louisbarryflorist.com@gmail.com', 'Promotion of Louis Barry Florist', 'Description of the Promotion', 'x2N8P0uo', 'DEFAULT_R2', 393),
('valbellamidtown.com@gmail.com', 'Promotion of Valbella Midtown', 'Description of the Promotion', 'YsEtprbW', 'DEFAULT_F2', 425),
('theflowersocial.com@gmail.com', 'Promotion of The Flower Social', 'Description of the Promotion', 'd6DCivwg', 'DEFAULT_R2', 806),
('umatemakeria.com@gmail.com', 'Promotion of Uma Temakeria', 'Description of the Promotion', 'HreptXwN', 'DEFAULT_R2', 824),
('flowercity.com@gmail.com', 'Promotion of Flower City', 'Description of the Promotion', 'i7L1gJ0b', 'DEFAULT_R2', 360),
('hallsoftaraflorist.com@gmail.com', 'Promotion of Halls of Tara Florist', 'Description of the Promotion', '6KnFGPe7', 'DEFAULT_F2', 296),
('cabrini181.com@gmail.com', 'Promotion of Cabrini 181', 'Description of the Promotion', 'cdjAyqpP', 'DEFAULT_R', 748),
('baharyfishmarket.com@gmail.com', 'Promotion of Bahary Fish Market', 'Description of the Promotion', 'ol0jEOUv', 'DEFAULT_F2', 471),
('eddiessweetshop.com@gmail.com', 'Promotion of Eddies Sweet Shop', 'Description of the Promotion', 'MnfY1cW8', 'DEFAULT_F', 865),
('baritalia.com@gmail.com', 'Promotion of Bar Italia', 'Description of the Promotion', 'gF2l8vtH', 'DEFAULT_F', 354),
('cestboncafe.com@gmail.com', 'Promotion of Cest Bon Cafe', 'Description of the Promotion', 'l7AKjHZY', 'DEFAULT_R2', 240),
('quentinpizza.com@gmail.com', 'Promotion of Quentin Pizza', 'Description of the Promotion', 'rLW5uhXP', 'DEFAULT_F2', 214),
('ujafederation.com@gmail.com', 'Promotion of Uja Federation', 'Description of the Promotion', 'ZUOrVTwh', 'DEFAULT_R', 225),
('stemsfloraldesign.com@gmail.com', 'Promotion of Stems Floral Design', 'Description of the Promotion', '5HTMec0N', 'DEFAULT_F2', 913),
('thelittleflowershop.com@gmail.com', 'Promotion of The Little Flower Shop', 'Description of the Promotion', '1oPbmYD9', 'DEFAULT_R', 545),
('flowercreations.com@gmail.com', 'Promotion of Flower Creations', 'Description of the Promotion', '7U9SCWci', 'DEFAULT_F2', 226),
('argan.com@gmail.com', 'Promotion of Argan', 'Description of the Promotion', 'vnPyVE8g', 'DEFAULT_F2', 236),
('thaiterminal.com@gmail.com', 'Promotion of Thai Terminal', 'Description of the Promotion', 'erDTsSP1', 'DEFAULT_R2', 707),
('milosyard.com@gmail.com', 'Promotion of MiloS Yard', 'Description of the Promotion', 'dvzX31qf', 'DEFAULT_R2', 388),
('diner.com@gmail.com', 'Promotion of Diner', 'Description of the Promotion', 'Jr0nuPyB', 'DEFAULT_R', 977),
('wasabisushibento.com@gmail.com', 'Promotion of Wasabi Sushi Bento', 'Description of the Promotion', 'gebiIAYS', 'DEFAULT_R', 374),
('cadaques.com@gmail.com', 'Promotion of Cadaques', 'Description of the Promotion', 'yPxYiFmA', 'DEFAULT_R2', 787),
('eddiejrssportlounge.com@gmail.com', 'Promotion of Eddie Jrs Sport Lounge', 'Description of the Promotion', 's5IJ9uhi', 'DEFAULT_R2', 697),
('doubledragonchineserestaurant.com@gmail.com', 'Promotion of Double Dragon Chinese Restaurant', 'Description of the Promotion', 'QSXqWRlO', 'DEFAULT_R2', 490),
('stroni.com@gmail.com', 'Promotion of Stroni', 'Description of the Promotion', 'hbJkCx1I', 'DEFAULT_R', 492),
('caterinapizza.com@gmail.com', 'Promotion of Caterina Pizza', 'Description of the Promotion', 'lfqW6rUa', 'DEFAULT_F2', 547),
('vai.com@gmail.com', 'Promotion of Vai', 'Description of the Promotion', 'LoGJ0FSM', 'DEFAULT_F', 915),
('umamishoppu.com@gmail.com', 'Promotion of Umami Shoppu', 'Description of the Promotion', 'VuNCgYUZ', 'DEFAULT_R2', 677),
('walton’sfancy&staple.com@gmail.com', 'Promotion of Walton’s Fancy & Staple', 'Description of the Promotion', 'ZMQtnuU0', 'DEFAULT_F2', 244),
('sunsetfloral.com@gmail.com', 'Promotion of Sunset Floral', 'Description of the Promotion', 'KNjdITDy', 'DEFAULT_F', 825),
('flowerswithessence.com@gmail.com', 'Promotion of Flowers With Essence', 'Description of the Promotion', 'ARfpcsQP', 'DEFAULT_R', 571),
('oh!bagelcafe.com@gmail.com', 'Promotion of Oh! Bagel Cafe', 'Description of the Promotion', 'pRQYcdhA', 'DEFAULT_R', 379),
('z&cjamaicancuisine.com@gmail.com', 'Promotion of Z&C Jamaicancuisine', 'Description of the Promotion', '3lkmG7cr', 'DEFAULT_F', 663),
('warrenhallcoffeebar.com@gmail.com', 'Promotion of Warren Hall Coffee Bar', 'Description of the Promotion', 'lg1PA7GO', 'DEFAULT_F2', 454);
