# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0
MAINTAINER admin
# COPY  path-to-your-application-war path-to-webapps-in-docker-tomcat 
COPY target/Lab_02-IEs.war /opt/tomcat/webapps/
